[chapter]
= 3: Bitcoin and its Doubles

§3.00 — The abstract to the 2008 Bitcoin paper reads (in full):

```
A purely peer-to-peer version of electronic cash would allow online payments to be sent directly from one party to another without going through a financial institution. Digital signatures provide part of the solution, but the main benefits are lost if a trusted third party is still required to prevent double-spending. We propose a solution to the double-spending problem using a peer-to-peer network. The network timestamps transactions by hashing them into an ongoing chain of hash-based proof-of-work, forming a record that cannot be changed without redoing the proof-of-work. The longest chain not only serves as proof of the sequence of events witnessed, but proof that it came from the largest pool of CPU power. As long as a majority of CPU power is controlled by nodes that are not cooperating to attack the network, they’ll generate the longest chain and outpace attackers. The network itself requires minimal structure. Messages are broadcast on a best effort basis, and nodes can leave and rejoin the network at will, accepting the longest proof-of-work chain as proof of what happened while they were gone.
```

§3.01 — Bitcoin coincides with a proposed subtraction. By dissolving the function hitherto attributed to a “trusted third party”footnote:[In his link:http://unenumerated.blogspot.de/2014/12/the-dawn-of-trustworthy-computing.html[introduction] to ‘The Dawn of Trustworthy Computing’, Nick Szabo describes the role of the ‘trusted third-party’ within the world’s existing electronic information infrastructure: “When we currently use a smart phone or a laptop on a cell network or the Internet, the other end of these interactions typically run on other solo computers, such as web servers. Practically all of these machines have architectures that were designed to be controlled by a single person or a hierarchy of people who know and trust each other. From the point of view of a remote web or app user, these architectures are based on full trust in an unknown ‘root’ administrator, who can control everything that happens on the server: they can read, alter, delete, or block any data on that computer at will. Even data sent encrypted over a network is eventually unencrypted and ends up on a computer controlled in this total way. With current web services we are fully trusting, in other words we are fully vulnerable to, the computer, or more specifically the people who have access to that computer, both insiders and hackers, to faithfully execute our orders, secure our payments, and so on. If somebody on the other end wants to ignore or falsify what you’ve instructed the web server to do, no strong security is stopping them, only fallible and expensive human institutions which often stop at national borders.” ] it realizes a flat network, in which all connections are P2P relations. Since the legitimating role of the third party – the extrinsic or transcendent element – is authentication of the originality of transactions, the network cannot be scoured of transcendence without “a solution to the double-spending problem”. The complicity of these twin goals is perfectly explicit: “What is needed is an electronic payment system based on cryptographic proof instead of trust, allowing any two willing parties to transact directly with each other without the need for a trusted third party.” Conceived as a project of political economy, this is what Bitcoin is.

§3.02 — The self-comprehension of Bitcoin, then, as already announced in the second sentence of the abstract, begins with the double spending problem – a concept so basic to all subsequent discussion that it demands abbreviation (to the ‘DSP’). Once again, a sub-division of the topic is in order. The DSP is (1) a highly-specific technical obstacle to the realization of any ‘trustless’ or decentralized digital currency, (2) a problem of extreme generality relevant to all monetary systems, roughly equivalent to fraudulence, (3) a re-formatting of the basic economic problem of scarcity for the epoch of Internet-based commerce, and finally – in its widest extension – (4) a crucial philosophical clue leading directly into the nature of the sign, and even re-founding rigorous semiotics (in the groundlessness of cybernetic self-reference).

§3.03 — Approaching Bitcoin as a solution to the DSP, in its narrowest and most functionally-critical sense, does not necessarily exhaust the significance of the protocol, still less its ripples of implication, but it undeniably comes close to capturing these in their essentials. It is in order to solve the DSP that Bitcoin innovates the blockchain, establishing – first in theory, then in implemented fact – the characteristic decentralization that defines it. Even features that are not, in principle, necessary to this solution, were in fact generated as more-or-less direct consequences of the approach that was selected to tackle it. For instance, while a simulation of metallism (and resultant rigid deflationary bias) is not strictly required for a blockchain-based digital currency, it follows as a matter of course from the way Bitcoin formalizes and resolves the DSP.

§3.04 — A prototypical form of the DSP afflicts even the very ‘hardest’ types of traditional money. Precious metal coinage can be debased through surreptitious adjustment of purity and magnitude – adulterated through admixture of inferior metals, reduced in size (by policy decision, executed through the mint), or attenuated through ‘clipping’ and ‘sweating’ (widespread practices of petty monetary fraudulence). The guiding strategy – or merely opportunistic tactic – in each case is that a certain quantity of gold or silver can be spent twice, traded as a sign, while economized as a substance. The fraudulent agent, whether government or private coin-clipper, exploits the door to duplicity inherent in the monetary character of the coin, according to which it operates as a sign of itself. The value of the coin has a double registry – the inscribed denomination, and the test of the weighing scale. Insofar as these two aspects of its worth can be prised apart, in some way that eludes convenient detection, precious substance can delegate its semiotic ghost to sustain the initial incarnation of its value, while taking on a second identity in another account. Insofar as money is a sign, the DSP shadows it, from its most primitive origin.

§3.05 — Paper money represents an immense semiotic liberation, and thus a corresponding accentuation of the DSP. The relation between inscribed denomination and metallic backing, no longer Janus-faced and intimate, yawns open. The distance is now bridged by an explicit promise, made in the name of a trusted authority, or monetary mediator. The immediate substance of the monetary sign – inked paper – is approximately worthless. The ‘paper’ of cash-money does not reference a commodity-substance, but a promissory vehicle. Value has been relegated to a word, in its contractual sense, historically consolidated through an evolution from the ownership titles (or ‘warehouse receipts’) issued by goldsmiths. Unsurprisingly, the ‘golden’ age of counterfeiting now begins. On the side of the legitimate monetary institutions and authorities, more exotic possibilities arise.

§3.06 — Even if fractional reserve banking – the principal financial business opportunity within a paper money economy – cannot be theoretically assimilated without reservation to the DSP, the resonances are, at the very least, uncanny. If not exactly spent twice, deposits are multiplied by lending.footnote:[The influential Rothbardian tradition of libertarianism consistently denounces fractional reserve banking as systematic financial fraudulence, structurally indistinguishable from counterfeiting (or fake money production). Within this political-economic context, the attempt to differentiate the DSP from a ‘double lending problem’ (DLP) might easily appear unnecessarily fastidious.] If this function is formally reversed, in the customary manner, reserves (liabilities) are required only to cover a determinate fraction of loans (assets), which allows the latter to be inflated at a rate reciprocal to the reserve ratio. (A reserve requirement of 10% permits a ten-fold credit expansion from the ‘monetary base’.) Political permission for the multiplication of deposits can, therefore, be directly inferred from mandatory capital adequacy ratios (through simple inversion). The normalization of the practice marks a radical discontinuity in monetary history. From this point onwards, standard banking activity becomes the predominant source of currency issuance, and cash is fused inextricably with debt through the root mechanism of credit creation.

§3.07 — The rise of banking is inseparable from an eclipse of cash. Even in the popular imagination, money loses all association with a hoarded commodity, as it is re-embedded in an account, where it exists solely as a ledger entry. Henceforth, the reliability of money as a store of value is seen to rest upon nothing more substantial than the integrity of institutionalized accounting procedures, which would subsequently – and in turn – be made conditional upon higher-level (political-administrative) monetary management. Since the inception of the electronic age, the digital transcription of financial ledgers has accelerated the trend, fostering explicit, widely-publicized dreams of ‘the cashless economy’. Cash-money becomes an increasingly marginal sub-component of credit flow, progressively ghettoized among atypically frictional, trivial, or disreputable money transfers. From the perspective of financial macro-management, its final abolition would be a consummation.

§3.08 — Fractional reserve banking partially anticipates macroeconomic governance in the discretion it affords to money creation, but – in itself – it offers only the faintest glimpse of the new world that is arising. This systematic incorporation of Keynesian ‘animal spirits’ into the realm of government policy objectives, beginning – very tentatively – in the 1930s, and then ascending to dominance in the post-war world, completes the politicization of the economic sign. Money is now invested with mass psychological meaning, identified with a technocratically-accessible dimension of collective arousal, and economic sentiment becomes an explicit object of administrative manipulation, through the money supply. The profundity of this development is easily under-estimated. In the era of macroeconomics, monetary policy is seamlessly fused with psychological operations, oriented to strategic public mood alteration or ‘demand management’ orchestrated with reference to an array of guiding concepts which are overtly attitudinal: ‘wealth effects’, ‘money illusion’, and ‘wage stickiness’ prominent among them. It is now the psycho-social propensities to save or spend that are to be theoretically reconstructed by the academic-administrative economic complex, with integral cynicism, on the functional analogy of pharmacological medicine. Economic and clinical therapeutics become increasingly hard to distinguish in principle, as they are differentiated only by their specific techniques of psychological intervention, and by the scales of their domains. In each case the (individual or collective) patient, vulnerable to ‘depression’, is subjected to expert treatment through the measured application of artificial ‘stimulus’. Feedback is provided by economic sentiment polling, designed to gauge business and consumer confidence. There is nothing metaphorical about any of this, except insofar as euphemism is called upon in the public presentation of monetary and fiscal objectives. Macroeconomic policy is – quite simply, and exactly – mass mind-control. As it is normalized, it sees ever less need to disguise the fact.

§3.09 — To remark upon a ‘double-spending problem’ at all in such a world, in which the very notion of intrinsic monetary integrity has been dissolved – with minimal remainder – into the politicized economy, replaced by the technopharmaceutical administration of financial dope, might easily seem comically (and no less tragically) Quixotic.footnote:[The understanding of the market order as a Quixotic cause, in all its anachronism, is captured by the link:http://www.amazon.com/Mises-The-Last-Knight-Liberalism/dp/193355018X[description] of Ludwig von Mises as ‘The Last Knight of Liberalism’ in the title to Jörg Guido Hülsmann’s intellectual biography. The Austrian perspective, within which Mises appears so obviously to be a defender of the capitalistic principle in a post-capitalist world, is itself reflexively captured by the Quixotic framing it explores, and thus rendered scarcely legible by its own untimeliness and social peculiarity. The oddity of our world is captures by the prevalence of a political-economic denunciation that targets ‘neoliberalism’ – in which Mises is implicitly entangled as a triumphant voice. Not only utter defeat, then, but a subsequent ‘restoration’ as a representative of that by which one has been defeated. This is the dialectic as dark humor.] It requires only the slightest deepening and darkening of perspective to see money, in itself, as a lost cause. No small part of the initial, catalytic excitement generated by Bitcoin is explained by this background of relentless hard money defeat.

§3.1 — In its attachment to the principle of pure economic theory, fastidiously intolerant of even nominal political compromise, Bitcoin is an experiment in Austrianism. When allowance is made for its abstraction from metallic coinage, it is Mises as operational code. While the fact that Bitcoin is happening is radically novel, necessarily, because it can only now take place – in the age of public key cryptography and proof-of-work credentials – what is happening is not new at all, or at least, the monetary model that Bitcoin implements in software is not. In the words of Pierre Rochard: “As Bitcoin adoption increases we will finally be able to ‘empirically validate’ what Austrians have been arguing for decades: 100% reserve banking with a scarce medium of exchange prevents speculative manias, financial crises, and economic depressions”.footnote:[link:http://nakamotoinstitute.org/mempool/fractional-reserve-banking-is-obsolete/[See].]

§3.11 — Yet, while the offense to hard-money economic philosophies presented by inflationary fiat currency – which has nourished Austrian criticism since the 1930s – continues to feed support into the Bitcoin project, its central role has been displaced by, and subsumed into, the formulation of the DSP. Discretionary state money-printing is only one special case of the far more general economic incredibility of signs. Technological, rather than political-economic dynamics, have played the decisive role in bringing this problem to its point of productive crisis.

§3.12 — Even if digital dematerialization is only ever an approximation, its economic consequences are concrete, and drastic. Since the ‘materiality’ of any product tends to operate inertially, dampening proliferation, the attenuation of materiality corresponds to a process of acceleration. Exponential decline in information costs, as captured by Moore’s Law,footnote:[While, strictly, Moore’s Law (initially proposed in 1965) concerns only transistor-density, it has come to serve as a general proxy for exponential trends in technology, and especially in electronics. The centrality of integrated circuits to the entire info-tech ecology ensures that Moore’s Law, even in its narrowest sense, projects a development curve of huge – and expanding – scope. In large part due to this, it is a predictive principle that lends itself to abstraction and generalization. (Ray Kurzweil’s ‘Law of Accelerating Returns’ or ‘LOAR’ is exemplary in this regard.) Under the name of Moore’s Law, the self-exciting circuit is established as the central model of techonomic process. It thus provides a kind of theoretical shorthand, enabling the widespread promotion of schematics for an ultramodernist meta-sociology, based upon the doubling-period, with accelerating variation as the sole constant. The nonlinearities propelling it include its own feedback into the processes it describes, as a ‘road-map’ – or, more accurately, a schedule – setting the pace of improvement in relevant technological specifications. Exponential technological improvement is normalized, and accepted as a benchmark. Acknowledgement of the trend becomes a causal factor in its own perpetuation. (Theory-practice orthogonalism is diagonalized.) In its loosest invocation, it corresponds approximately to run-away techno-commercial deflation. Macroeconomic capture of industrial deflation is the principal political-economic story of the Keynesian epoch. Capitalistic surplus is ‘nationalized’ through currency issuance. The imperative to ‘fight deflation’ – inspired by Great Depression mythology – lends this process of systematic appropriation a perverse moral dignity. Automatic valorization of money – through capital (or ‘total factor productivity’) improvement – is compensated by centralized monetary management, benchmarked to price stability. Within this epoch, therefore, Moore’s Law describes a process of systematic economic expropriation, by monetary authorities, of those gains from advances in industrial productivity that would otherwise be distributed spontaneously to consumers (by falling prices, i.e. deflation). Electronic money reverses this tendency. ] implies informational explosion. The trend corresponds to a second (and numerically tractable) sense of the ‘Californian Ideology’ war-cry: “information wants to be free”.footnote:[According to link:http://en.wikipedia.org/wiki/Information_wants_to_be_free[Wikipedia], the slogan is attributable to Stewart Brand, uttered in a remark at the first Hackers Conference, in 1984. Whatever the utopian suggestion that might have been heard in this slogan, it would eventually be drowned out by the dark counter claim: _It is the destiny of any open near-zero-cost communication system to be spammed into dysfunction._] If the concept of ‘liberty’ is irreducibly hazy and controversial, while also prone to irresolvable metaphysical complications, that of cost suppression is definite and quite precisely accountable. Evidently, the preservation of scarcity under conditions of digital instantiation is a peculiar challenge, for the obvious reason that electronics enables the replication of perfect copies at near-zero cost. Prior to the theorization of this problem in monetary terms, it had been noisily exhibited by disputes over the digital ‘piracy’ of media products, corresponding to an unprecedented practical crisis in the regime of intellectual property.

§3.13 — The final (or near-final) subtraction of substantial expense from money production is conceptually clarifying. It prompts – or sharpens – the demand for a solution to the central problem that has haunted money since its beginnings. Once the proliferation of signs is freed from all serious inhibition, semiotic tokens of scarcity are catapulted into a climax state of vulnerability, and the DSP is exposed with unprecedented starkness.footnote:[The commercial value of any transaction depends upon its exclusivity, which opens directly into questions of identity. The idea of a ‘digital signature’ – a very closely-related pseudo-paradox – binds identity and value to the suppression of fraudulent duplication. To repeat Satoshi Nakamoto’s critical formulation (Bitcoin #2): “We define an electronic coin as a chain of digital signatures.”] It is here, at the furthest antipodes from metallic commodity money, that a peculiar folding – into simulation – restores the gold model to a central position in monetary theory, and, more consequentially, money production.footnote:[In the words of the Bitcoin paper (#6): “The steady addition of a constant of amount of new coins is analogous to gold miners expending resources to add gold to circulation. In our case, it is CPU time and electricity that is expended.”] It is precisely because Bitcoin no longer represents gold, however indirectly, that it is able to simulate gold, with such extreme (abstract) fidelity that it can be said – persuasively – to exceed gold in its most relevant monetary features, including even that of scarcity, alongside communicability, divisibility, and verifiability. As a simulation, Bitcoin necessarily produces an artificial substantiality in the course of its solution to the DSP, and ultimately as its solution. The critique of duplicity is indistinguishable from an ontological experiment.

§3.14 — The DSP originates from a ‘fact’ so basic that it crosses from the order of (empirical) actuality into that of (transcendental) principle: Signs are cheap. To substitute a sign for a thing, a signification for a demonstration, is an economization. It is commonly said ‘that is easy to say’, and – relatively speaking – it is. At the first-order level of cynical amorality – or of pure game-theoretic rationality – it pays to break promises, which cost so little to make, and yet may be arbitrarily expensive to keep. This alone suffices to suggest why there cannot be signs without an implicit problem of trust. The consequences are double-edged. Economization of any kind – getting the same for less, or more for less – is positively adaptive (or selectively promoted) to such an extent that evolutionary processes are indistinguishable from the formation and transformation of codes. Inherent to the economy of code, however, is a vulnerability to exploitative messages, which seize upon the exorbitant efficiency of the sign as a resource (or meta-resource) to be appropriated. Genetic code invites virus. Zoosemiotics invite mimicry.footnote:[Among the most striking examples of specifically zoosemiotic parasitism are instances of Batesian mimicry (named after the naturalist Henry Walter Bates, 1825-92). Typically, these involve the adoption by a non-toxic species of markings indicating toxicity, and thus an evolutionary strategy of free-riding upon acquired, and broadcast, unpalatability. Bates discovered the phenomenon, after noticing the remarkable similarity of coloration in certain non-related butterfly species. The semiotic convergence, he theorized, was driven by adaptive imitation. Signs ‘backed’ by poisons were easy to imitate, and thus allowed species to advantage themselves of the signal, while economizing on the original bio-chemical ‘message’. Such fraudulence, naturally, has its costs to the original, toxic species, who now find the signal communicated by their markings diluted. A process of semiotic inflation begins to work itself out.] Linguistic expression invites deceit. Money invites the DSP. The sign is co-emergent with duplicity.

§3.15 — Bitcoin’s solution to the DSP is the blockchain, or ‘public ledger’ – a decentralized record of transactions which selects-out all non-original (or duplicitous) payments. Only the first instance of any bitcoin deduction from an account is validated, and preserved. All duplicate payments – cases of double spending – are edited out of the blockchained reality-record, automatically, through rejection of those inconsistent blocks in which such defects occur. Simply by protecting itself against splits – or forks – the blockchain constitutes a consistent plane of Being, upon which any particular being can be what it is, and nothing else instead, or besides. Positive absence of duplicity is thus an efficient ontological criterion, or selective principle. The blockchain is pre-determined to construct reality in such a way that fraudulence will not have taken place. That alone remains real which is consistent with the integrity of identity-money, or potential value.footnote:[The language of ‘potential’ is rejected in the name of contingency by a recent variety of transcendental philosophy associated in particular with Quentin Meillassoux and (in its financial application) Elie Ayache. For these thinkers, the projection of possibilities – or probabilities – is itself a transcendent illusion, constituting a metaphysics that is subject to critique. We are unable to follow Ayache into an employment of critique that ventures without discernible hesitation into the hyperbolic, in that it construes market pricing as simply incalculable (and even, on the inverse face – where it is theoretically captured as a stroke of ‘writing’ – as something close to a divine power). Pricing discovers nothing within the Ayache account, unless its own status as a truly sovereign decision, coincident with the genesis of being (the ‘event’). ‘Potential’ is used here in its physical sense – potential energy and ‘potential difference’ (voltage) – which is to say, real tension, or capacity (for work). Insofar as the concept of disequilibrium is ‘flattened’ by that of contingency, the consequence is massive information destruction. Potentials exist (virtually) prior to their probabilistic formalization. They are not epistemological productions. Followers of Elie Ayache, who can be expected to balk at this modal vocabulary, are also unlikely to find their concerns assuaged by the mere assertion that it is only derivatively related to probabilistic models, while primarily referring to something else entirely, namely free energy, or productive capability, as designated (and quantified) prior to its actual employment or consumption. Statistical mechanics – even in its abstract conception and its far-from-equilibrium application – provides the bridge between the science of probabilities and the capacity to do work. Crudely stated, abstract industrialism is here counter-posed to hyperbolic financialism, under the (post-duplicitous) sign of the machine. The industrialization of money, driven by Bitcoin, demonstrates a deep teleology very different to that manifested in the evolution of financial assets through ever higher sublimities of derivation.] Only the non-duplicitous will have really occurred, as perpetually re-evidenced by the synthetic past that is reproduced on the blockchain, as a consistent artificial memory, endorsed by Nakamoto Consensus, beyond which no superior tribunal can in reality exist. The blockchain is demonstrably capable of making itself real. In this way it departs from all merely conceptual or ideological assertions of ontological grounding, while implicitly dispensing with the political superstructures through which such assertions are concretely propagated. The reality criterion it introduces takes the form of an automatic – which is to say non-negotiable – law. The force of this law is derived from what can be, rather than – directly – from what is, or what ought to be. There is no double spending on the blockchain because there cannot be.footnote:[Just, as for Kant, the causal consistency of nature is a matter of transcendental necessity rather than empirical fact, so the absence of double spending on the blockchain ‘follows’ inevitably from what the blockchain is. To understand the blockchain is already to know (as a matter of transcendental principle) that the DSP is thereby resolved. ]

§3.2 — The Bitcoin paper consists of twelve short sections, including an introduction and conclusion. It is compressed to a minimal summary at this point, although discussed in pieces throughout the book, and rehearsed at slightly greater length in the first appendix. The emphasis here is critical, oriented – as is the paper itself – to the dissolution of the DSP, and thus the construction of a plane of transactional immanence, from which all transcendent elements (or “trusted third parties”) have been evacuated. The transcendental argument of the Bitcoin paper runs as follows:

§3.21 — The “trust based model” is expensive, socially frictional, and vulnerable to fraud. To overcome these problems, Bitcoin proposes the substitution of “cryptographic proof” for “trust” (which is to be obsolesced by irreversible crypto-commitments). The elimination of trust-based mediations reduces transaction costs. The system remains resilient in the absence of oversight, so long as a predominance of applied “CPU power” is controlled by “honest nodes”.

§3.22 — An “electronic coin” is defined “as a chain of digital signatures”, which is equivalent to “a chain of ownership” (this is described later, in the conclusion, as the “usual framework” for crypto-currency construction). The elimination of the need for a “trusted third party” (or “mint”) requires that transactions be “publicly announced” within a system that enables “participants to agree on a single history of the order in which they were received”.

§3.23 — Bitcoin’s synthetic history draws upon established procedures for digital time validation, using a timestamp server to chain its hashed blocks in succession. “Each timestamp includes the previous timestamp in its hash,” constructing an artificial history as a robust series of envelopments – or ordered swallowings – “with each additional timestamp reinforcing the ones before it.”

§3.24 — The timestamped blocks are secured against tampering by proof-of-work locked hashes.footnote:[Adam Back’s link:http://www.hashcash.org/[Hashcash] system (1997) provides the model. The use of a proof-of-work test – earning a Hashcash stamp – to eliminate spam by pre-emptive vetting of costless messages, contributes a solution of equal efficacy against DoS (denial-of-service) attacks. See subsequent discussion in this chapter.] Such irreversibility is at once a deployment of cryptographic asymmetry, a consummation of contractual integrity, and a realization of (time-like) successive order. Notably, it is isomorphic with a thermodynamic – or statistical mechanical – gradient.

§3.25 — The network reproduces itself through a six-step block creation cycle. Since nodes “always consider the longest chain to be the correct one”, synthetic history, as an ordinal-quantitative variable, functions as a (selective) ontological criterion. Accepted blocks provide the building material for the subsequent cycle of network reproduction.

§3.26 — Bitcoin builds incentives into its infrastructure. Nodes are automatically compensated for the work they perform maintaining the network through the issuance of new coins. The system thus attains techonomic closure. The horizonal finitude of the Bitcoin money supply necessitates an eventual transition to payments based on transaction fees. Well-organized incentives also fulfill a security function, by motivating potential attackers to support rather than subvert the network.

§3.27 — Blocks can be compressed to economize on memory demand by pruning Merkle Trees. Moore’s Law is invoked as a realistic projection of exponential decline in digital memory price over time, moderating the requirement for information parsimony.

§3.28 — Further economy is offered by a payment verification short-cut (involving a modest sacrifice of security in exchange for added convenience).

§3.29 — Bitcoin transactions contain multiple inputs and outputs, to facilitate the integration and disintegration of coins during transfers.

§3.291 — Bitcoin radically adjusts the structure of transaction privacy. Rather than drawing a curtain of obscurity between a transaction and the world, in the traditional fashion, it nakedly exposes the transaction to public scrutiny. The new line of concealment is drawn between the transactional agents and their off-line identities, at the precise boundary of the commercium, therefore, and no longer within it. Secure masks are proposed as the new basis of privacy protection, coinciding with the anonymity of public keys.

§3.292 — The prospect of a successful attack upon the blockchain diminishes exponentially with the addition of “honest” blocks. An attacker therefore has a window of opportunity, which closes at a rate based on the block-processing capacity of the network.

§3.293 — The conclusion, summarizing the entire argument, is a masterpiece of lucid intelligence. (It is reproduced in its entirety in Appendix-1.)

§3.3 — Grasped abstractly, the most powerful functional innovation of the Bitcoin protocol is the binding of currency issuance to the servicing of system integrity, which twists the process into a consistent circuit. It is this loop that enables the protocol to achieve autonomy, or – in a reflexive articulation – self-reliance. Because industrial incentives cover all regulatory requirements, self-reproduction is embedded within the process of bitcoin production. The protocol makes it impossible to produce bitcoins without automatically policing Bitcoin. Primary wealth extraction cannot take place without verifying transactions – through the validation of blocks – and thus tending the system as a whole, consistently and comprehensively (as if with an invisible hand). Stated succinctly, Bitcoin instantiates immanent economic government.

§3.31 — This auto-productive economic security circuit is evidence for the fundamental integrity of the Bitcoin blockchain. Currency and distributed public ledger are a single functional system, with neither making coherent operational sense without the other. This is a point made with exceptional cogency by Bitcoin commentator ‘Joe Coin’:

_Given the crucial requirement to preserve decentralization, the problem Satoshi had to solve while designing Bitcoin was how to incentivize network participants to expend resources transmitting, validating, and storing transactions. The first step in solving that is the simple acknowledgement that it must provide them something of economic value in return. … The incentive had to be created and exist entirely within the network itself … any instance of a blockchain and its underlying tokens are inextricably bound together. The token provides the fuel for the blockchain to operate, and the blockchain provides consensus on who owns which tokens. No amount of engineering can separate them._footnote:[link:http://www.joecoin.com/2015/02/crypto-20-and-other-misconceptions.html?m=1[Source]. The importance of this argument is almost impossible to over-estimate.]

§3.32 — The threshold crossed here is both subtle and immense. Retrospectively, it will have been almost nothing, since the techonomic circuitry it invokes was – now demonstrably – already the operational principle of modern civilization (capitalism). It is only through Bitcoin, however, that the essential techno-commercial integrity of capitalism is brought into crisp focus, and extracted from speculative debate. When the machine is theoretically apprehended, ‘holistically’, as a real individual – or, far more consequentially, implemented as such – neither its technical nor its economic ‘aspects’ can be diverted into transcendence, or contingency, as extraneous, mutually-independent factors. Incentives are inherent to the machinery.footnote:[A (2014/10/29) tweet by Balaji S. Srinivasan describes the diagonal succinctly: “Bitcoin allows algorithms to act on incentives.” ] In a sense more complex – and involving – than anything the harsh paradox of the term immediately communicates, Bitcoin is a purposive mechanism. The conclusive action of the Bitcoin system – block validation – which seals each cycle of its reproduction, is a non-decomposable teleo-mechanical step (a diagonal escalation, or transcendental synthesis). It is industrialism, the mechanizing market, distilled to a previously unrealizable quintessence.

§3.33 — ‘Capital’ means – simultaneously and indissolubly – technological assets (machine-stock) and comparatively illiquid money (investment). Between these twin aspects there is only formal (and not real) difference. Their real integrity is demonstrated by techonomic machinery. The economic analysis of capital is diverted through technology, since wealth cannot be grasped substantially except in its cycle through productive apparatus, but technological analysis is drawn, reciprocally, into economics by the integration of rewards into the machine. At the level of philosophical reflection, under the cognitive conditions inherited from its mainstream European traditions, such techonomic integrity is difficult to hold together. To fuse mechanical causes with behavioral incentives in a techno-strategic assembly is to meld registers that have been determined as mutually inconsistent since antiquity.

§3.34 — Techonomic apprehension runs into a direct collision with the commanding dualism of the modern mentality, by insisting upon a re-animation of the compact between efficient and finalistic action. According to the complacent tenets of the new (or ‘enlightened’) cultural settlement, based upon the drastic demotion of scholasticism and its displacement by a substitute theo-scientific division of labor,footnote:[That which is settled by the formalization of techno-political compartmentalization is, of course, the great war of religion that inaugurates European – and thus global – modernity. In a way still stronger than that outlined by Max Weber in his The Protestant Ethic and the Spirit of Capitalism (1905), self-propelling industrialization coincides with a break from the Catholic civilization of the West. The consolidation of an immanent techonomic principle (‘growth’ or positive cybernetic nonlinearity) presupposes a drastic contraction of the sphere of ecclesiastical cultural authority. Capitalism is that, by essence, which is not answerable to anything beyond itself. Its incremental actualization, therefore, presupposes social fractures, from which superordinate moral agency has receded. Among the major civilizations of the world, only Europe – under the impact of Reformation – realized this condition during the early modern period. A broken religion is a basic requirement of modernity, which Protestantism pioneered uniquely. (The work of David Landes explores this catalytic dissociation in detail.) Modern social institutions thus formalize and entrench a disconnection between what is and should be. Science is freed, in principle, to tell ugly truths. Engineers are freed to devise machines whose purposes the uncontaminated dynamic of capital accumulation alone dictates. Modernization calls for nothing other than this. The division of labor, or authority, between (traditional) religious doctrine and (modern) techno-scientific investigation is philosophically consolidated into the distinct spheres of practical and theoretical reasoning (to employ the Kantian vocabulary, as concretely instantiated in the topical differentiation between the first two Critiques). In very recent times, this enduring demarcation is faithfully reproduced – without notable modification – by Stephen J. Gould’s conception of Non-Overlapping Magisteria (NOMA), which divide religion and science, values and facts, in the same way, and with the same crypto-political emphasis upon jurisdictions. Given the historical status of this argument, as a near-perfect restatement of the original critical settlement, laid down in the final decades of the 18th century, it is surely extraordinary that Kant is nowhere mentioned in Gould’s link:http://www.colorado.edu/physics/phys3000/phys3000_fa11/StevenJGoulldNOMA.pdf[essay].] the bridge from mechanism (cause-effect) to teleology (means-end) had been definitively dismantled. Each was henceforth to be compartmentalized within a distinct, wholly independent dimension. Their sole residual relation was orthogonal (or demarcated). The realms of directed liberty, and of instructed mechanism, were to be perfectly isolated from each other, and mutually withdrawn beyond all possibility of reciprocal interference. In this arrangement was to be founded the modern peace, of no lesser consequence than that of Westphalia, and something close to a genuine social contract. Through it, an amoral techno-science was co-produced beside an agnostic politics. Two complementary templates for expertise arose, each pledged to silence in the house of the other. This compact has been at once the condition for the gestation of an autonomous industrial power, and – on exactly the same grounds – an obstacle to its cognitive digestion. With the surfacing of the concealed techonomic entity, it buckles, loses coherence, sheds explanatory credibility, and undergoes accelerating social desanctification. Modernity’s axial, though predominantly inexplicit, concept of the mechanical instrument – whose self-contradiction had been concealed as if within a collapsed dimension – escapes its bonds and re-emerges to break the basic categories of Occidental thought. That is where we are now.

§3.35 — The intellectual crisis stimulated with ever-increasing intensity by techonomic escalation (that is, by capitalism, or efficient critique), has fertilized a luxuriant foliage of ‘deconstruction’. Yet, the untenability of orthogonal conceptuality does not necessitate a subsidence into cognitive dilemma, or aporia. Even when the problem is restricted within the narrow bounds of its philosophical formalization, it opens a positive path – pursued since the inception of the process – into diagonal action, or individuation. It is surely implausible to decry as ‘unthinkable’ what has been demonstratively operationalized. Bitcoin attests to such a process with each cycle of block validation and Nakamoto Consensus. The process demands something structurally and functionally indistinguishable from transcendental philosophy, insofar as it is to be constituted – even very approximately – as a coherent object of thought. What it makes of this ‘philosophy’, however – as it pushes through upgrades into successively ultra-radicalized immanentizations – is rarely self-advertized as such. What it apparently offers, instead, is ‘technology’ – a term that is a near-exact synonym for ‘instrumental mechanism’, and one that undergoes comparable internal schism, across the same conceptual rift.

§3.36 — In any approach to the techonomic entity – plotted as if from outside – the notions of emergence (or individuation), diagonal process, teleo-mechanical causality, integral nonlinearity, and transcendental escalation begin to exhibit a general inter-substitutability. All of these things, among many others, are convertible by simple transforms into immanentization, or the real operation of critique. An efficient side-lining of pseudo-transcendence – achieved by way of a dynamic flattening – is the reliable signature of the trend. The solution to the DSP is a diagonalization.

§3.4 — The Bitcoin DSP-solution unshackles (digital) proliferation from duplicity, in the production of replicable singularity. As with every diagonal construction, this outcome is pseudo-paradoxical, since it reformulates an apparent contradiction. From the latent matrix of abundant signs and scarce things, it extracts the scarce sign. Through this procedure, crypto-currency is implemented as critique. It coins a diagonal concept, not as impractical-contemplative ‘theory’, but as working code.

§3.41 — Duplicity – or the DSP – is primarily registered as a monetary problem, in the guise of counterfeit currency, and secondarily as a problem of identity authentication, responding to impersonation. On the Internet, however, another manifestation of the same basic syndrome has been far more prevalent, socially advanced, and technically provocative. The critical driver, on the path to a cryptographic solution to the DSP, has been spam.

§3.42 — ‘Spam’ is narrowly defined as a species of advertising adapted to the conditions of near cost-free electronic communication. Its first large-scale manifestation was ‘unsolicited bulk email’ (UBE), a sub-category of the more general phenomenon of the ‘electronic spam’ which exploits the receptivity of instant messaging systems, newsgroups, mobile phones, social media, blog comments, and online games, among others. While advertising is the principal motivation for this massive duplication of unwanted – and typically only vaguely directed – communications, spam procedures (and supportive technologies) can also be employed for DoS (denial-of-service) attacks, which are designed to overwhelm a specifically-targeted recipient with an inundation of messages. At a sufficiently abstract level of apprehension, no strong boundary of principle differentiates advertising spam from a denial-of-service (DoS) attack, except that the former is generally divergent (one-to-many) and the latter convergent (many-to-one). The residual distinction is motivational. The injury (cost) to the recipient that is an inevitable side effect of spam promotion (‘collateral damage’) is a primary objective for the DoS assailant.

§3.421 — ‘Spam’ – abstractly conceived – spontaneously expresses the consequences of extreme information economy, or radical dematerialization, and is thus emblematic of electro-digital semiotic crisis. It follows the Law of the WORM – write once read many (times) – into a near-costless replication explosion. Unsurprisingly, any recipient of electronic communications is vulnerable to spam harassment, generating a problem that tends to ubiquity. The arms race between spammers and spam filters is recognizable from that characterizing the cross-excitation of infections and immune systems in the biological sphere. Cheap sign contagion is the common syndrome. As the various Turing Test-type defenses attest, any effective obstacle to the automation of spam production increases its cost. The time taken to ‘prove you are human’ adds friction at the point of terminal message delivery, where it cannot be easily eliminated – pre-emptively – by the spammer. Such ad hoc defenses necessarily aim to raise messaging cost, in order to restore the signal of commitment that digitization has erased.

§3.422 — The difference between a solution to the DSP and a spam filter turns out to be somewhere between subtle and non-existent. Both respond to the destructive consequences of semiotic economy – cheap signs – as these climax within networked, digital electronics.footnote:[Spam’ invites a very general definition as the spontaneous expression of digital economics (or near-zero cost communications). The Wikipedia link:https://en.wikipedia.org/wiki/Email_spam[article] on email spam makes the point well: “Since the expense of the spam is borne mostly by the recipient, it is effectively postage due advertising.” The Internet Society attributes the term to the celebrated Monty Python comedy sketch depicting the widely-derided tinned meat as “ubiquitous and unavoidable”. Estimates of the cost of email spam vary wildly, with the high-end figures reaching over US$100 million annually, for US businesses alone, by the early years of the 21st century. Global spam volume in 2011 is thought to have exceeded 7 trillion messages. The illusion of costlessness is illustrated starkly by the phenomenon of spam, through the revelation of an unanticipated trade-off. Whatever is free is abused. If an activity with discernible externalities can be pursued without definite commitment, it tends to produce a tragedy of the commons (see Chapter 3). Microscopic private utilities within a zero-cost matrix generate an explosion of informational pollution. Abundance theories, therefore, have special cause to be intellectually disturbed by the phenomenon. Spam is a toxic Cornucopia.] The critical step in this respect was taken by Adam Back in 1997, with hashcash, a proof-of-work based messenger credentials system. As Back describes the innovation: “Hashcash was originally proposed as a mechanism to throttle systematic abuse of un-metered internet resources such as email, and anonymous remailers in May 1997. … The hashcash CPU cost-function computes a token which can be used as a proof-of-work.”footnote:[link:http://www.hashcash.org/papers/hashcash.pdf[See]: ‘Hashcash – A Denial of Service Counter-Measure’ (2002).]

§3.423 — Rather than offering another piecemeal response to some particular spam problem, Back’s solution looks more like an attempt to fix the Internet, or even more than this. Hashcash tackles the spam problem at its source (cheap signs). Rather than defensively fending off ever more cunning spam intrusions, it enables a positive signal that someone has taken the trouble to communicate this, with the ‘trouble’ being attested by proof-of-work certification. This solution can be seen as a basic filter. It works as an admission pass, rather than a policing operation. The cost of duplicity is raised at the root, which involves the DSP being grasped as the root.

§3.424 — The very name ‘hashcash’ attests to the realization that proof-of-work certification is self-monetizing. Evidence of effort – when this is pre-formatted as a signal of commitment – has intrinsic potential value, independent of its application. A currency is initated automatically, and all that remains is the process of price-discovery. Bitcoin provides a framework within which this process can occur.

§3.43 — However tempting it might be to construe proof-of-work as an algorithmic reprise of the labor theory of value (an LTV 2.0),footnote:[Proof-of-work as a foundation for commercial value echoes a theme that has reverberated through the tradition of political economy. It leads, by scarcely-resistible digression – onto an associated track of exceptional historical richness, which is the analysis of value-creation as work, or labor time. From Smith to Marx, this has been a conceptual commitment that closely coincides with classicism in economic theory. Subsequently, the power of the marginalist – and especially Austrian – analysis has tended to entirely overshadow the intellectual labors of the objective value theorists, and even to topple them into derision. Marginalism threw its political-economic precursors into eclipse due to the evident superiority of its transcendental foundations, even if this articulation of its success found no corresponding acceptance within professionalized economic study. From the critical perspective, the objectification of the (subjective) negative utility of effort can only appear metaphysical. Its historical supersession, in this regard, follows predictably from its essential – and rigorously intelligible – error.
It would be unfortunate, nevertheless if a type of Whig-historical triumphalism were to obliterate all understanding of the genuine theoretical insight now entombed with the Labor Theory of Value (or LTV). Most basically, the LTV already incorporates an important critical-subjectivist insight. This can be stated in different ways. Conceived in terms of power, it is the recognition that money does not primarily overcode inanimate resources, but rather represents a distributed system of command (though one rendered inconspicuous by its intrinsic exit-option). Wealth is bound by exchange equivalences to static assets only because it quantifies a capacity to direct activity. It crystallizes compliance. The ‘normal’ economic evolution in the direction of services makes this reality explicit, from the side of consumption. An analogous subjectivization is recognizable in regards to utility (value). Commercial incentives – including those at work in the labor market – can be theoretically systematized as an economization of effort. The value of a possession is the incarnated advantage of no longer having to struggle to obtain it. The critical reversal here is blatant, and crucial. Within the Marxist tradition it is understood as the disillusioning of a fetishization. It is not the thing, but the difficulty of its acquisition, that establishes the foundation of its value. This is an insight, of course, whose foundations were solidly established by the earlier classical economists, Ricardo most notably. The LTV, it can be seen, is a critical relief from naïve objectification, even if it is also – in well-understood respects – a perpetuation of it.
When pursued in detail, however, whether as a matter of economic theory or industrial practicality, fixing the relation between time and work has proved daunting. Quantification of work on the basis of standard time units exhibits an obvious dependency upon chronometric technology. This, in itself, suffices to identify the topic as distinctively modern. Beside comparatively accurate time-measurement, the practice of compensated labor time also requires some adequate degree of work monitoring. It is necessary to know both how much time is spent working, and that this time is spent working. In practice, these requirements have been understood as demands for oversight, regardless of the ideological characteristics of the industrial regime in question. Solutions to the informational problems of work monitoring have been institutionalized within the factory organization of production, integrally, originally, and necessarily. Such systematization of proof-of-work within an anthropological context reaches its most remarkable expression within the methods of Taylorism, which from a theoretical perspective is only an elaborate social hack. The time-and-motion analysis required for ‘scientific management’ is stubbornly intractable to political-economic abstraction (of a kind sufficient for rigorous conversion into monetary quantities), and no practical advance of conceptual significance has occurred subsequently. Immanent proof-of-work, despite its supposed manifestation in the commodity – as exchange value – eluded both ‘bourgeois’ political economy and its socialist critics. The production of measurable (human) labor time has proceeded alongside its theoretical analysis, within a semi-parallel, partially interactive, historical dynamic. This is investigated, within the tradition of Marxist historical sociology, by E.P. Thompson, in his link:https://libcom.org/files/timeworkandindustrialcapitalism.pdf[essay] on ‘Time, Work-Discipline and Industrial Capitalism’. He is meticulous in noting that “a severe restructuring of working habits” has been practically inseparable from the relevant “changes in the inward notation of time”. That theorization has not proceeded in this case from the inside out, is the critical historical materialist insight. Labor time was a distributed, experimental, piecemeal process, before it was a political-economic conception.
Karl Marx’s maxim for socialist compensation “to each according to his work” achieves an ironic actualization in the Bitcoin reward system. All power to distributed hashing capability!] it is not from political economy that Bitcoin derives its sense of ‘work’ – unless by extraordinary circuitousness – but from computer science. The work to be proven, in the validation of a block and associated currency issuance, is performed by a CPU in the course of a mathematical puzzle-solving exercise, and demonstrated through successful execution of a computational task. It is the final measure – beyond which no appeal is possible – of the contribution made by any node to the running of the network. Such work is probabilistic, rather than deterministic. There is no application of computational effort that can strictly guarantee reward. The work required of the miner is persistence in pursuit of a low-probability outcome, through repeated trials. It is both structurally and genetically related to a process of stubborn cryptographic attack – ‘hacking’ in its colloquial, though not traditional, sense – and also to a grueling search for success in a lottery-type game of chance.

§3.431 — Proof-of-work is accomplishment at a test, which can then be employed as a key. In the case of Bitcoin, it simultaneously ‘unlocks’ new bitcoins and casts a ‘vote’ that counts towards the consensual updating of the blockchain. Incentive and service are nondecomposably married. Optimal functionality is achieved by making the content of the test entirely meaningless. It serves as a demonstration of brute force (trial-and-error) computation, inherently resistant to rationalization, and thus irreducibly arduous. It is not a test of cognitive achievement, in any general or sophisticated sense, but solely of computational effort. Its sole ‘significance’ is its difficulty. Despite the obvious risk of anthropomorphism, it might even be described as an ordeal, or – less dramatically – as a trial, unambiguously demonstrating commitment.

§3.432 — Would it not be preferable to have this ‘work’ also (i.e. simultaneously) applied to a problem of intrinsic value?footnote:[In the link:http://unenumerated.blogspot.hk/2017/02/money-blockchains-and-social-scalability.html[words] of Nick Szabo: “The secret to Bitcoin’s success is certainly not its computational efficiency or its scalability in the consumption of resources. Specialized Bitcoin hardware is designed by highly paid experts to perform only one particular function – to repetitively solve a very specific and intentionally very expensive kind of computational puzzle. That puzzle is called a proof-of-work, because the sole output of the computation is just a proof that the computer did a costly computation.”
“Very smart, but also very wasteful,” is the way one exemplary critic link:http://ideas.4brad.com/paradox-bitcoin-proof-work-mining[describes] the proof-of-work concept. “All this computer time is burned to no other purpose. It does no useful work – and there is debate about whether it inherently can’t do useful work – and so a lot of money is spent on these lottery tickets. At first, existing computers were used, and the main cost was electricity. Over time, special purpose computers (dedicated processors or ASICs) became the only effective tools for the mining problem, and now the cost of these special processors is the main cost, and electricity the secondary one. … What this means is that the cost of operating Bitcoin is mostly going to the companies selling ASICs, and to a lesser extent the power companies.”
link:https://wiki.nxtcrypto.org/wiki/Whitepaper:Nxt[Resonantly]: “In mid January 2014, statistics maintained at blockchain.info showed that ongoing support of Bitcoin operations required a continuous hash rate of around 18 million GH/sec. During the course of one day, that much hashing power produced 1.5 trillion trial blocks that were generated and rejected by Bitcoin miners looking for one [of\] the magic 144 blocks that would net them $2.2 million USD. Almost all Bitcoin computations do not go towards curing cancer by modeling DNA or to searching for radio signals from E.T.; instead, they are totally wasted computations.” Crypto-currency pioneer ‘Wei Dai’ is link:http://www.weidai.com/bmoney.txt[emphatic] about the importance of teleological purification to efficient proof-of-work schemes: “The only conditions are that it must be easy to determine how much computing effort it took to solve the problem and _the solution must otherwise have no value, either practical or intellectual._” [My emphasis.\]] In its most positive formulation, this question has been a stimulus to altcoin differentiation. Anything other that mining might do, beside sheer block validation, seems to indicate an unexploited seam of surplus value. Such suggestions are strictly analogous to a recommendation that gold prospecting be bound to valuable activities of some other kind (such as fossil hunting). On the basis of fundamental economic principle, they merit the most vigilant suspicion, since they amount to a deliberate confusion of cost calculations, promoted in the name of a superior – or at least supplementary – utility. Yet however much the costs of mining are strategically muddied – and in fact, in some complex fashion, cross-subsidized – they still need to be unmuddied, to exhibit an economically-intelligible commitment. Mining investment is a signal, which cannot be dissolved into extraneous purposes without destruction of critical information. To whatever extent bitcoin miners are generating bitcoins by accident, is also the degree to which their contribution to Nakomoto Consensus, or block validation, is devalued. The perfect pointlessness of bitcoin generation procedures – for anything other than Bitcoin system consolidation (as remunerated in bitcoins) – is a feature, and not a bug. Cybernetic closure, or self-reference, is its own reward, and it is only as such that it acquires distinctive monetary characteristics. As always within the terrain of auto-production, this is the inescapable abyss, or principle of immanence. The self-propagating circuit has no ground beyond itself, and can only be impaired by the attempt to provide one. 