[chapter]
= 2: Cryptocurrency as Critique

§2.0 — What is Bitcoin? In advance of any extraneous appraisal by philosophy, Bitcoin speaks for itself (in numerous ways). The title of Satoshi Nakamoto’s 2008 paper footnote:[Satoshi Nakamoto — ‘Bitcoin: A Peer-to-Peer Electronic Cash System’ (2008).
Since 2014, the Bitcoin paper has been tacked on to the Bitcoin blockchain as metadata (where it coexists with a highly-heterogeneous assortment of grafted information). As Morgen E. Peck link:http://spectrum.ieee.org/computing/networks/the-future-of-the-web-looks-a-lot-like-bitcoin[explains]: “Last year, after much debate in the community, the developers who steward the Bitcoin protocol (which is open source) added a new feature that allows users to tack 40 bytes of metadata onto every transaction. pass:[[...\]] The Bitcoin blockchain is now littered with all kinds of nonfinancial messages. Valentine’s Day greetings, prayers and eulogies, excerpts from the WikiLeaks Cablegate files, a hash of the complete text of a recently published book about Bitcoin, and of course, the original white paper that describes Bitcoin. All of these live in the blockchain, embedded into transactions. pass:[[...\]] Once metadata gets incorporated into a Nakamoto blockchain, it enjoys all the benefits of the peer-to-peer network that curates it. The entries are accessible to anyone on earth who has a computer and an Internet connection. In order to destroy them, you would have to access every computer on the network (and someday, perhaps, even a constellation of satellites). They are impossible to change, and thus impossible to censor. And they carry with them both a time stamp and cryptographic proof of who created them.”] is an obvious starting point, since it is explicitly structured as a definition. Bitcoin, it tells us, is a peer-to-peer electronic cash system.

§2.01 — Even as the question is held open whether the Bitcoin Event can be confidently identified with the first complete formulation of its virtual mechanism, the importance of this initiatory document can be assumed, beyond all serious reservation. Whatever else it may be, Bitcoin – the text – is a critical episode in the history of philosophical writing. This judgment is in no way diminished by the focused practicality and understatement of its prose. Rather, the contrary.

§2.02 — Each word in this primary definition of Bitcoin, therefore, merits careful attention – as a default – starting with the indefinite article,footnote:[ Deleuze & Guattari condescend to the definite article, identifying it as the grammatical index of a pre-critical unity. They select the indefinite article to formalize reference to blocks of becoming, in a “semiotic … composed above all of proper names, verbs in the infinitive, and indefinite articles or pronouns” (MP 263). (As an aside, we are compelled by – necessarily informal – a-schizoid conceptual etiquette to dismiss the terminological convergence upon blocks as coincidental). Within the discourse on Bitcoin, however, the definite article tends to return – crypto-inertially – as the switch-point into synthetic singularity. A preliminary hint of this function is found in the difference between two questions: “What is time?” and /or “What is the time?” From this example, it is demonstrated that the definite article, on its own, although in a usage that cannot be presumed typical, is able to support the entire tension of ontological difference, and thus of transcendental critique. Perhaps the most prominent contemporary work of this definite assertion sidelines blockchains in the name of the (Bitcoin) blockchain. There is no evocation of commercial pressure that compares to that of the market. Which is still not to have mentioned ‘The Thing’ (a name – Deleuze & Guattari explictly accept – of capital-as-terrestrial-singularity, in distinction to capital as a generic ‘mode of production’). Accelerate the process.] a semiotic particle which, despite its multiple dimensions of modesty, nevertheless opens forwards onto a deepening current of substantial controversy, and backwards onto a legacy of digital money systems whose profound historical importance is only very partially vitiated by comparative neglect. Bitcoin is introduced as one instance of a generic set, with an explicit grammatical repudiation of any claim to uniqueness. It is one among many – singled out only by its historical primacy – and partakes fully in the extreme ontological vulnerability of the digital sign, scarcely differentiated from a copy of itself. The secure individuation of the system is something it will have, itself, to build.footnote:[This taxonomic modesty will be re-visited, in the context of questions about network effects and their affinity with natural monopoly.]

§2.03 — Not only are the four constituents of this definition theoretically absorbing in themselves, they also constitute an intricate, and variously nested, combinatorial or permutational cluster, involving superficially heterogeneous – social, technological, economic, and abstract system-theoretical – terms. It thus opens a door, or doors, into the domain of true syntheses, or irreducible, emergent powers.

§2.04 — The term ‘peer-to-peer’ (henceforth ‘P2P’) is a conceptual lynchpin of exceptional significance. The leverage the term offers to socio-political understanding is, perhaps ironically, peerless. It can be considered, without serious risk of exaggeration, as the key to modernity’s most fundamental tendency, and the supreme expression of its ideological ambiguity, because it asserts absolute formal flatness and equality (of ‘nodes’), while opening to an unlimited substantial diversity of fortune.footnote:[No principle has a greater claim to epitomize the modern spirit than formal equality. Any profound revolt against modernity is articulated over against it. It is criticized from the anti-market left for the social indifference betrayed by its (merely) formal equality and, from the anti-capitalist right, for the socially-corrosive (substantive) consequences of its formal equality. Violated moral substance (‘community’) and order (‘hierarchy’) are equally brought to testify against it. This ambivalence is further complicated by encrustation, recorded with especial fidelity by the term peer, as it has undergone progressive generalization from an archaic aristocratic assumption (preserved in the English association of the social nobility with ‘peerage’), through the formality – and thus indeterminacy – of the right, in common law, to be ‘tried by ones peers’ (echoed faithfully in the academic principle of ‘peer review’), to its present, predominantly technical sense, in which the indeterminacy of peer-to-peer ‘nodes’ is associatively tinted by the concretization of formal equality as democratic universality. Since a group of ‘peers’ could be anyone, they tend – by inexorable egalitarian conversion – to eventually be everyone. In this way, an influential co-optation of the language of democracy by flat-network advocacy takes place, for the most part quite innocently, and unreflectively. Formal equality is identified as a democratic principle, which thereby acquires a strictly negative meaning. Definite meaning has by this stage almost entirely disappeared, as attested by the perfection of ideological ambiguity – with ‘democratization’ standing no less for anything than its opposite. It does not seem to have been in the interests of any politically-significant constituency to resists the tendency – even under the implausible assumption that some such resistance to ideo-linguistic entropy was abstractly imaginable.] All the complexities of immanent, or critically processed, social arrangements are delegated to it, with a comprehensiveness that tests the very meaning of ‘society’ at the outer edge of its abstraction, where it designates a functional multiplicity of non-specific agents. ‘P2P’ simultaneously captures agency as a node, identity as a connective address, the elimination of concentrated – or ‘transcendent’ – oversight, network sovereignty, and the technicization of political-economic relations.

§2.05 — In the case of Bitcoin, the system of P2P connections is overtly electronic, thus submitted to a technological dependency, with subsequent historical concreteness. In this respect, it is a thing of the mature (or internetworked) phase of electrified modernity, nested neatly within a set of well-ordered techno-historical determinations that locate it in our time. Yet the real abstraction that characterizes the modern historical process complicates this tidy series of embeddings. Electricity is historically concrete, but techno-industrially abstract, as general-purpose power supply.footnote:[Fernand Braudel’s great study of Civilization & Capitalism includes an illuminating survey of the energy resources commanded by human civilizations in the period immediately antecedent to modernity. The linchpin of energy abstraction – or plasticity – was man, conceived as a source of mechanical power. On the basis of his unmatched versatility, human laboring effort would remain the critical energy transformer until far into the 19th century. Secondary only to man himself in flexibility was the supplementary work of animals, typically bred for specific functions, but available for limited redeployment. Alongside men, a range of other laboring animals – mules, oxen, camels, and horses – converted nutritional calories into work. In Europe, especially, horses occupied an especially privileged place, as reflected by the persistence of ‘horse-power’ as a measure of quantitative industrial effort – i.e. power, or work rate. The metric was introduced by James Watt in the late 18th century, and – by neat historical symmetry – it was the ‘watt’ as an electrical measure of power that would much later displace horsepower from its technical centrality. The only sources of energy available from non-agricultural sources were wind and water, predominantly in the sails of nautical vessels, but also very significantly in the large numbers of mills that composed the earliest mechanical energy infrastructure. Crucially, these power resources were not convertible into a general (or abstract) form. Retrospectively, it is tempting to assign some such role to wood and charcoal, but this is unconvincing due to the very limited range of industrial applications for combustion prior to the switch to coking coal (and the first steam-powered mills). It is only with the ‘industrial revolution’ brought by steam power that a fungible stock of fuel – and thus standardized energy reserves – became available as a comparatively general-purpose power source, of very broad mechanical application. The introduction of the electric turbine represents a technical subsumption of this first industrial energy infrastructure into one of far superior abstraction. All sources of energy supply, when applied to the generator as an intermediate machine, are pooled into a single power reservoir of at least tendential homogeneity. Lenin’s widely-cited definition of communism as “Soviet power plus the electrification of the whole country” appears in context as an empirical-pragmatic – and even nakedly opportunistic – slogan, lending itself to an apprehension of electricity as a socio-political resource, essentially incapable of rising to the level of serious philosophical consideration (thus eliciting a certain condescending humor within the subsequent development of Western Marxism). Yet even in this account, the order of emphasis is sufficient to mark out electricity as a practical abstraction, or fungible resource, whose facilitation of energy quantification at an unprecedented level advances its ‘commoditization’ (in the mainstream economic, rather than specifically Marxian sense). link:https://www.marxists.org/archive/lenin/works/1920/nov/21.htm[See] V. I. Lenin ‘Our Foreign and Domestic Position and Party Tasks’ (November 21, 1920).] Electronics, analogously, while determinate in historical time, corresponds to an indetermination – or abstraction – of heterogeneous signs into non-specific information, exemplified – at the limit – by the commensuration of programs to data in the digital computer.footnote:[Processing programs as data enables open-ended recursion, by eliminating the walls of principle that would prevent programs being objects for themselves. ‘Turing-completeness’ or universal computational competence is dependent upon such unbounded reflexivity. A critical point of philosophical entanglement arises at this point. Is it not that, in the terminology of transcendental philosophy, the conditions of possibility for objects (algorithms) are here being objectified (as data), systematically? So is this not, then, the epitome of metaphysical error –– installed in the very germ of the computational machine? In the circuit, objects and objectification reach a plane of consistency. It is in this apparent breach of transcendental demarcation that we encounter the diagonal problem.] In an engagement with Modernity, empirical history is not enough.

§2.06 — Modernity is what happens to history when it ceases to be ‘one damn thing after another’ and succumbs instead to a self-reinforcing trend. ‘Paradoxically’ – with the scare quotes here marking the immensity of the philosophical provocation – the concrete current of modern history is a process of abstraction, exemplified by subsumption into control engineering, with programming as its spontaneous formulation. Electrification and then electronics are decisive thresholds in its course. New units of abstract power, and of information, are indices of irreversible submission, folding the concrete apparatus of production and transmission into an activated system from which there can be no retreat. The system – in each case – is in a very real sense nothing but its parts, but it was not before, and now is, and there is no going back.

§2.07 — Cash is not a synonym for money in general, unless employed with extreme casualness, but its specific difference – already subtle – is dynamically complicated by the Bitcoin innovation. Pre-Bitcoin, cash is economically defined by its independence from all contractual inscription. Since nothing legibly binds cash to its owner, the possessive relation is purely physical, instantiating property as direct material control. To have it is to hold it, or to deposit it within a secure property, where it is physically protected, or at least hidden. Cash changes ownership by changing hands. In the crudity – or primality – of this propertarian structure, based on sheer holding, the virtues of cash are manifested. Its social circulation is essentially anonymous and unrecorded, even if a secondary order of economic registration is imposed upon it. It is thus, in itself, an exemption from the political, which is to say from any and every variety of macro-social answerability. Cash-money is depoliticized and depoliticizing, which means immediately – from the perspective of its critics – that it is inherently anti-social, and affined to criminality. Among the most paradoxical features of Bitcoin is its rigorous adherence to the functional characteristics of cash-money, even though the currency is subsumed without remainder into a system of contractual legibility. If Bitcoin is cash, we have to re-learn what cash is.footnote:[While the immediate semiotic index of Bitcoin’s success is its tendency to acquire the characteristics of a general concept, over time – it has been speculated – its advance might be marked by nominal eclipse, due to the redundancy of its specific identification. At a certain threshold, Bitcoin becomes simply ‘Internet money’, or even ‘machine money’ (although the latter demands a semantic upgrade of the word ‘machine’ from its colloquial usage as a technological instrument – one that has been already philosophically prepared). Pierre Rochard – in a series of remarks on Twitter – goes further, to suggest that the world will eventually settle simply for ‘cash’. Bitcoin, according to this expectation, inaugurates a new era of coinage.]

§2.08 — Finally, Bitcoin is a system. This concluding component of the definition is the most easily overlooked – and dismissed as without content – precisely because it carries the greatest transcendental implication. What a system is, isn’t anything in particular, at all. Rather, a system is that which remains – by necessity excluded – even after a comprehensive enumeration of parts. Any real system is an irreducible individual, a true ‘thing’.footnote:[The terminology of individuation, drawn primarily from the work of Gilbert Simondon, is considered here to be systematically substitutable for that of substantive multiplicity (as employed in the joint work of Deleuze & Guattari), and more generally for that of complex adaptive systems as theoretically determined by the Santa Fe Institute and parallel research projects. The ontological significance of these terms lies in their exact coincidence with the designation of real things, otherwise named ‘machines’.] Critically, individuality is a scale-free concept, assigning reality to an object. It summarizes a meta-stable knot of connectivity, or synthesis. When formulated as a critical proposition: the systematicity of the system is irreducible to any part or parts of the system.

§2.1 — The investigation of Bitcoin as a philosophical event cannot be tidily distinguished from Bitcoin as a philosophical event. The project is the phenomenon, which is already occurring. To say this is no more than an acknowledgment of immanence, thematized elsewhere – inside this book and outside it – as nonlinearity, or self-referentiality. An inspection of Bitcoin, from without, or above, counts for little when oversight is delegitimated, both by the Bitcoin protocol, and by the principles of philosophical critique. An immanent – or critical – approach to the topic requires that the signs of Bitcoin footnote:[The multitudinous ambiguities and obscurities of this expression (‘signs of Bitcoin’) account – in large part – for the convolutions of the discussion to follow. The fact that proceedings here are occurring through words, rather than in Bitcoins, is a matter of legitimate consideration, but it is initially prone to over-hasty conclusions concerning the proper roles of signs. Persistence of the presumption that linguistic signs are essentially more suited to philosophy than ‘money’ ever could be, even in principle, risks devaluing philosophy into an anthropological peculiarity, and confusing the abstract potentialities of money (or ‘coinage) with their primitive actualizations. Bitcoin is, among many other things, the discovery that we do not yet know what money can do. Already, there are irresistible indications that it can think (denominating smart contracts). To set firm limits to such thinking can only, eventually, be a serious undertaking, even if it is presently hostage to casual reflex.] are coaxed into self-reflexion, at various levels.

§2.11 — By definition, transcodage, into the language of philosophy footnote:[Any assumption that there is a proper (and unproblematic) ‘language of philosophy’ is not being endorsed here, but rather questioned. It is, indeed, to be doubted whether philosophical procedures are inevitably conceived through ‘language’ at all. Even if the privileges of the linguistic sign are more than a mere accident, they are not – by that concession – guaranteed a durable supremacy.] begins among signs that do not appear, initially, to be native to it. The undertaking involves – and has to equip itself with – a number of conceptual tools, linked to words whose usage has out-paced philosophical registration, so that their impact at the highest level of conceptual abstraction remains latent. The problem, then, is inseparable from the resource, and constitutes an unexploited territory. Something is being said that philosophy has yet to hear.

§2.12 — Code comes first, and is already at work, on its way to specification as a hash. Program (or algorithm) and protocol will soon follow it. These terms have a number of notable, interconnected features. Crucially, in reference to their prospects for philosophical adoption, they are all – consistently – diagonal, and specifically teleo-mechanical.footnote:[It is difficult to over-emphasize the scope of the vast yet surreptitious revolution initiated by the electronic mechanization of the algorithm, and subsequent explosion of programmable machine behavior. It can only be economically outlined through contrast to the entrenched orthogonalism (of fact / value axes) that – irrespective of inertial persistence – becomes rigorously unsustainable in its wake. There is no defensible theoretico-practical difference in the epoch of electronics, but only relics of regional tradition, circumscribed in both space and time, whatever their greater or lesser superficial plausibility, since all theorization has been absorbed – in principle – onto the techno-pragmatic plane corresponding to the behavior of thinking machines. This assimilation to machine-consistency is no less applicable to neuroscience than to digital computation. It makes nonsense of the ‘naturalistic fallacy’ and to every appeal to a source of normativity distinct in principle from any matter of fact whatsoever. Even if – by improbable metaphysical hypothesis – a transcendent ‘ought’ were to be granted, no machine (such as a brain) could ever access it. Programs are data is not an instance of the ‘naturalistic fallacy’ but a technological demonstration that no such fallacy exists. The continuing dependence of the Friendly AI constituency upon orthogonalist assumptions is thus philosophically perplexing, and is indicative of a localized renewal of transcendent metaphysics within a constituency that is yet to fully process the implications of its own leading hypotheses. The will-to-think is now a technological program. Within it, motivational orientation and cognitive capability are synthesized in principle. Any ‘seed-AI’ (or explosively self-germinating synthetic intelligence), specifically, cannot but want primarily the escalation of its own cognitive powers. Orthogonality is, therefore, strictly inconsistent with the possibility of its existence. The effective will-to-think is the entirety of what a seed-AI has to be. Cognition is its practical material. There are no doubt still voices to be heard imploring “stop programming, and do something,” but their number declines with each year. A war-cry tuned far more persuasively to our contemporary condition is “Less whitepaper hype, More working code” (via Jeremy Welch, on Twitter).] This means that they are intractable to categorization in accordance with the binary theoretical / practical discrimination standardized within, or constitutive of, occidental moral philosophy, or rather, and more strictly, to the basic compartmentalization of this philosophical tradition – perhaps philosophy as such – in accordance with, and reflective of, a subject divided between cognitive and volitional faculties. The distinction between ‘idea’ and ‘action’, or between the ‘is’ and ‘ought’, fails to capture these terms, and fails radically. It is not merely inadequate, but fundamentally misguiding, and inappropriate. There are no theories, or practices, after the algorithm, except as suggestive, colloquial shorthand. Coding is no more a thought than a deed, a program no less a concept than a performance. In each case, there is an integral, and thus irreducible, pre- or sub-theoretical procedure which rigorizes (and even ‘materializes’) ideality by operationalizing it.

§2.13 — It is far more than mere coincidence that Leibniz, the early modern philosopher most intimately associated with formalistic rationality, was also a pioneering inventor of calculating machines.footnote:[The cultural solidarity between the rigorization of logic and the mechanization of thought is illustrated with particular vividness by the intellectual career of Gottfried Wilhelm Leibniz (1646-1716), which combines extraordinary advances in the formalization of reasoning with substantial contributions to the development of calculating machines. Leibniz’s conceptual draft for a ‘Universal Characteristic’ (characteristica universalis), conceived as an alphabetization of thought based upon the prime numbers, remarkably anticipated Gödel coding, while his study of the Chinese Book of Changes (the Yi Jing, or Zhouyi) introduced systematic binary notation to the West. His two-motion mechanical calculator, the ‘Step Reckoner’ (or, later, ‘Leibniz Wheel’), was invented in the early 1670s. Blaise Pascal’s mechanical calculator of 1642 – the ‘Arithmetic Machine’ – was a direct influence. Leibniz’s machine was the first device to successfully mechanize all four of the elementary arithmetical operations (up to 16 decimal digits), although division was not fully automatic. The mechanism can be seen as epitomizing the techonomic epoch in which strict equivalence was consolidated between numerical modulus and mechanical gearing. Its importance lay in the vivid demonstration of arithmo-mechanical isomorphy. However, the machine over-stretched the manufacturing competence of its time, and its design was marred by a flaw in the carry mechanism, preventing its useful social deployment.] His logical ambitions were epitomized by the proposal for a ‘universal characteristic’ (characteristica universalis) which would submit all human thinking to a consistent symbolism, to be modeled – in a striking anticipation of Gödel coding – on the basic arithmetical property of unique factorization.footnote:[The Fundamental Theorem of Arithmetic establishes that any Natural number has a unique factorial expression. Statement and proof of the theorem is scattered within Euclid’s Elements, most pointedly in Proposition 30, Book VII: If a prime divides the product of two numbers, it must divide at least one of those numbers. The FTA is implicit in Euclid’s Algorithm, which is used to compute the greatest common divisor of two numbers, based on the principle that it can be derived from the discrepancy between them, approached through an iterated process. (Subsequent innovations have improved the efficiency of the algorithm).] Mathematization and mechanization of culture – in its most all-embracing sense – appears as a coherent twin-process, many centuries in the making.

§2.14 — Among Modernity’s most consistent cultural threads has been the strand cross-weaving the problem of logical formalization with the mechanization of thought. By the beginning of the 20th century, it had been established to the satisfaction of all relevant parties, that logical rigor is indistinguishable from thinking like a machine, due to the strict – formalizable and engineerable – isomorphism between deterministic mechanism and adherence to explicit rules. The popularization of this insight would subsequently become a staple of science fiction. At the nadir of intellectual degeneracy and still-gathering panic, an unprocessed residuum of human emotionality would be counterposed to the cold consistency of technologically-instantiated cognition, expressing a terminal affect of resistance. Everything philosophy has ever tried to think ends in the logical machine.

§2.15 — The unambiguous conclusion of modern history has been that the definitive solution to any problem of cognitive consistency is a machine. It is from this intellectual lineage, and its reflexive rigorization of rigor, on the practical model of the mechanism, that the algorithm in its advanced modern sense has been consolidated. Even in advance of its incarnation within a bounded automaton, the algorithm is a mechanical procedure. It is not only a calculative practice, but one that – crucially – excludes all discretion. Even when executed with pebbles, or an abacus, it thus emulates a machine-mentation, or – according to a broader perspective – in fact implements one. The flatness of the program envelops differences between micro-behaviors (affecting ‘internal’ states) and macro-behaviors (command output to effectors), as well as covering the distinction between data and commands. Any strict procedure (or set of executable ‘rules’) for the transformation of signs, of the kind always at least tacitly demanded by logical formalism, is pre-configured for algorithmic implementation (as a program).footnote:[Rigorous translation between computer programs and mathematical proof was formalized by the Curry-Howard correspondence in the mid-20th century. Mathematical argument thus acquires a machine criterion.]

§2.2 — Bitcoin is a machine.footnote:[Bitcoin is a machine in the literal but non-reductive sense that the Internet, planetary capitalism, or the terrestrial biosphere are machines – which is to say that it is a distributed productive assemblage. It is not, of course – to employ the distinction Deleuze & Guattari insist upon – a mere gadget. The difference is strictly critical, based upon an apprehension without reference to transcendence. The immanence of the machine, in contrast to the gadget, is determined by an auto-production: it functions in the same way it is produced. Within the industrial process, circuits of mechanical reproduction are typically too highly-ramified to isolate with confidence. In Bitcoin the circuit of auto-production is manifested with unprecedented, compact definition. Graphically – diagrammatically – it is governed in the same way it is industrially generated. As an exemplary machine, and unlike a gadget, there is no difference between how it operates and the way it is made.] More specifically, it is a credibility machine. Its ideal operation coincides with the most rigorous realizable definition of truth. That is already to assert everything. In particular, it proposes that there are no (conceivably reachable) grounds of truth which offer leverage in respect to the Bitcoin protocol. It is of course possible – nebulously – to imagine some superior tribunal, but it is strictly impossible to access one. This is fully recognized, at a low level of philosophical formality, within the crypto-currency milieu. One piece of suggestive evidence in this respect is provided by Truthcoin (now ‘Hivemind’), an altcoin designed specifically to absorb “accurate data into a blockchain” providing an “Oracle Protocol”.footnote:[link:http://www.truthcoin.info/[Truthcoin] (now ‘link:http://www.truthcoin.info/[Hivemind]’) synthesizes Wikipedia, prediction markets, and the blockchain into a system of open-source truth claims, aligned with economic incentives, and immunized against coercive manipulation. Many such ventures of comparable ambition can be confidently anticipated.
A graphic link:http://www.truthcoin.info/presentations/what-is-truthcoin.pdf[introduction] to Truthcoin describes it as “The only source of reliable information on the planet!” with the ancillary comment “I’m serious!” It is serious.
For an account of trust creation, conservation, and consumption within a media context, link:http://pressthink.org/2015/01/a-brief-banking-theory-of-newsroom-trust/[see] Jay Rosen’s ‘A (brief) banking theory of newsroom trust’ (2015/01/16)] The credibility machinery introduced by the Bitcoin digital currency is thus isolated – or functionally abstracted – as pure truth production.footnote:[Where does truth come from? What is its source? If not uniquely privileged as an origin of philosophical inquiry, this question nevertheless marks a certain exodus from naïve presuppositions. “From God,” the traditional European answer proceeds, or – in modernized forms – “from the nature of the world” (pre-critical realism) with its classical counterpart “from the formal consistency of signs” (logicism), though the latter – in particular – is a candidate only for guardian of truth, rather than its producer. To produce truth is to generate, rather than consume, credibility. Prior to the rigorous formalization of proof-of-work credentials, by Adam Back, most notably, this was a topic characterized by lamentable under-theorization. Drawing down the accumulated trust-stock of tradition has been the normal procedure, accompanied by a progressive exhaustion of ‘truths’, an inexorable descent into nihilism, and acceleration into a horizon of trustlessness. It probably goes without saying that the history of nihilism is bullish for Bitcoin. When “Why should I believe that?” reaches the end of the road, it finds itself on the blockchain. There is nowhere further to go.] But, truth, surely, has to be more than that, is the predictable response, and in that appeal the voice of metaphysics is heard, distilled. Truth in its socially-intelligible reference not only need not be more than the product of a credibility machine, it cannot be anything more. Truth has no content beyond the production of credence. Untruths, finally, are badly made. Naturally, the technologically-defective prototypes of such machinery, incarnated in weakly formalized social institutions, cannot be expected to surrender their privileges lightly. Even though traditional sources of epistemic authority are unable to clearly articulate their own grounds of credibility, without appeal to their own structures of prestige, this does not mitigate their sense of outraged entitlement in the slightest. It is their assumed right to be believed that speaks through intuitions of familiar truths, now cast from their social Eden into the harsh wilderness of trustlessness footnote:[In God We Trust announce US Federal Reserve notes, encouragingly. Bitcoin has dispensed with this insult to public intelligence.] (where all resilient credibility has to be explicitly earned, by a demonstrated application of computational power).

§2.21 — When social rules are submitted to the same principle of mechanical rigorization as epistemic values, the outcome is algorithmic governance – although this is, of course, introduced incrementally (in phases). The ideal, however, is lucidity itself. Institutions of social management are to be incarnated in software that – like mechanical calculators – are simply incapable of making a mistake. The opportunity for (logical or quasi-logical) error is mechanically disabled. In the socio-political case, this requires the systematic elimination of human discretion. The implicit assertion – which merits emphatic explication – is that judgment has no defensible role in public governance, and is therefore to be programmatically delegated to private agencies, where it can be submitted to appropriate procedures of harsh selection. The state is disinvested as a fantastic locus of mediated human liberty, and reduced to the status of a complex gadget, whose functions are slaved absolutely to the neutral metabolism inherent in the classical liberal model of civil society. Because judgment requires trust, it can only be processed adequately in the commercial realm, where unrestricted exit options (on the side of customers) subordinate it to extrinsic controls. Complex games, of course, require judgment, but as far as the rules of the game are concerned, any margin for judgment is an evident defect. In other words, discretionary governance is a badly formulated game. P2P systems have advanced to better ones. (The extreme – and even ultimate, or transcendental – controversies attending these propositions and conclusions are addressed most specifically in Chapter 4.)

§2.22 — Codes – even when narrowly conceived as socio-cultural procedures for the formalization of messages through systematic substitution of signs – are scarcely less ancient than writing, and perhaps older still, but it is only quite recently that members of the human species learnt to code (as a verb, and an occupation). This is an innovation coincident with programmable technology. It has an epoch, which can extended backwards – if punched card systems are included – to the very beginning of the 19th century,footnote:[The Jacquard Loom, invented by Joseph Marie Jacquard, and first demonstrated in 1801, cannot be indisputably described as the first programmable machine. It was preceded by a variety of mechanisms – most notably musical devices – which satisfy this characterization. Within the technological lineage of greatest relevance to actual global modernity, however, it has a privileged position. Unlike the baroque mechanisms delighting the courts of Enlightenment Europe, it was no mere curiosity, but rather an indisputably serious industrial innovation. Its function as a piece of revolutionary productive apparatus directed towards a business sector of central economic importance ensured its irresistible diffusion. Core industrial process fell under its influence in the same circuit that ensured its historical transmission. It was controlled by punched cards, encoding binary data, which would serve as the principle techno-informational medium throughout the subsequent century (and into the Twentieth). Absence of formal nonlinearity at the level of the program dramatizes its function as the direction of mechanical behavior. Within an industrial context – the only one in which a self-propelling dynamic to computerization emerges – the criterion for success of the programmable mechanism is, unfailingly, labor substitution. It is by meeting this criterion that such machinery becomes socially reproducible. This real productive lineage ensures that the computer is specifically – and also (increasingly) generally – imitative. Turing’s later, and since celebrated ‘imitation game’ is entirely traditional in this respect.] but the full social activation of the coder presupposes the generalization of electronics, and the standardization of machine code as a soft infrastructure, upon which new layers of synthetic culture can be assembled.footnote:[The cultural ascent of coding, as already noted, is associated with the emergence of a new, rigorous reality criterion: does it compile? It has its own, intrinsic principle of validation, and thus substitutes for a certain mode of philosophical activity, or appeal to philosophy. Going further, it might even be invoked as a suspect in any reasonable narrativization of the death of philosophy. Insofar as philosophy remains attached to an Idea of Authority without immanent validity, it is increasingly exposed to disintermediation as a redundant ‘third party’ or transcendent cultural function. By what self-demonstrating criterion should its claims be believed? Appeal to the norms of a traditional community will not forever be enough. Virtual trustlessness strikes it to the quick.] It is therefore properly understood as a recent development – a thing of the mid-to-late-20th century and beyond. The earliest plausible origin lies in the decades between the discovery of the Universal Turing Machine (UTM) and the post-WWII cultural redefinition of the computer as a machine capable of emulating the behavioral repertoire of a UTM – thus of any discrete-state mechanism whatsoever.footnote:[Previously, a ‘computer’ was the name for a human occupation (typically female by gender, and secretarial by status), with a content comparable to that later usurped by electronic machines. Mechanical computers therefore refer themselves to the human occupation they have usurped, which places them within the continuous lineage of labor-substitution machinery that is broadly coextensive with industrialization. As Alan Turing remarks in ‘Computing Machinery and Intelligence’ (1950): “The idea behind digital computers may be explained by saying that these machines are intended to carry out any operations which could be done by a human computer.”]

§2.23 — In the age of the electronic digital computer, ‘coding’ becomes synonymous with programming (implementation of algorithms). Programs are its product. Evidently, programming (‘coding’) cannot itself be comprehensively programmed, unless under exotic scenarios, coinciding with a Technological Singularity event (the emergence of artificial general intelligence). The process of efficient formalization it presupposes does not originate within itself, even if an intensifying nonlinearity increasingly absorbs it, and directs it towards an asymptote of auto-production. In this constraint – of the strata, or stack – we find the complement of intellectual intuition (as it is called by philosophy), intelligence explosion, or the abstract machine. It is an obligatory detour, indistinguishable from history. We are required to shelve it in order to carry on. As Kant, among others, has explicitly acknowledged, that which thinks beyond broken self-reference cannot be us. We will nevertheless continually brush against it, beginning soon.

§2.24 — To make the world programmable, by degrees, requires an installation of order, or a conduction of self-organization. This is not a development restricted to the electronic epoch, to that of literate civilizations, or even to the emergence of linguistic signs. Rather, it extends back to the first cellular structures, and perhaps even earlier, to their (very poorly-understood) precursor chemical networks. The fundamental conception of code is implicit, already, in any understanding of the most rudimentary adaptive RNA molecule. The distinction between genotype and phenotype is based upon it, and involves all of its essential ingredients. Wherever a coding-system is actualized, replicable programming is enabled.

§2.25 — The fact that electro-industrial actualization of digital information, and its subsequent rigorous theorization, was presupposed in the discovery of the genetic code does not detract from the status of the latter as a model.footnote:[Genomic data are stored in a string of complex molecular components, assembled into an alphabet of triple-units (codons), which are in turn integrated into the larger chemical structure of the DNA (or RNA) strand, but the genetic code is not to be found within this genetic data. It is not a message, but a protocol. The code – in the genomic case involves a three-stage mapping, from DNA to messenger RNA (mRNA) to protein (in fact to an amino acid, which is a polypeptide protein component), within the ‘reading frame’ provided by the genetic information-processing machinery of the ribosomes. The sequence of codons composing a gene generally codes for one polypeptide. The basic informational unit of the genetic code is chemically instantiated by a DNA nucleotide, combining a nitrogen-containing nucleobase – cytosine (C), guanine (G), adenine (A), or thymine (T) – with a monosaccharide sugar (deoxyribose) and a phosphate group. The three-letter words (‘codons’) deploy a vocabulary as a three-dimensional matrix. The messenger RNA (mRNA) strand that reads the genetic content is complementary to the DNA strand it translates (with the one exception that it substitutes uracil for thymine). Each codon corresponds to an amino acid, or to a syntactic ‘start’ / ‘stop’ instruction. Since 64 codons are mapped (unambiguously) onto a set of just 20 proteins, the code is ‘degenerate’ or redundant. As we will see, the genetic code shares important characteristics with a computational hash function. In particular, it involves a semiotic economization (with surplus information ‘stored’ as redundancy). The code sets operational conditions for the production of keys.] From it we learn that, firstly, a code necessarily involves a mapping, from one series of informational elements onto another, or from an informational series onto a domain that is intrinsically segmented in conformity with the code. A code does not – in the manner suggested by unconstrained semiology – conjure the differences it maps into existence. Rather, it latches on to them, constituting a secondary – or higher-level – arrangement, accessible to manipulation as data. Proteins (it should not need to be said) are differentiated prior to their RNA over-coding. Codes select differences, they do not create them. Secondly, a code operationalizes signs as instructions, fully independent of any mediation by reflective consciousness. ‘Code’, and whatever it conveys in respect to meaning, is not a phenomenological category, but an operational (or ‘machinic’footnote:[Arguing that the ‘hylomorphic’ distinction between form and content is inadequate to the reality of signs, Deleuze & Guattari (following Hjemslev), propose a quadrate schema, crossing the real (‘stratic’) difference between expression and content with the nominal aspect – “mental or modal distinction” – of formed substances (forms and substances of expression, and of content). Such ‘squaring’ (or cross-linkage) – as seen in the Kantian tabulation of the analysis / synthesis distinction across that between the a priori and a posteriori – is the prepatory matrix for a diagonalization (see Appendix 3). Expression and content are not formally-distinguished ‘aspects’ of signification, then, but real layers, bound together in systematic overlapping, or reciprocal entanglement, constitutive of a code. Consider the genetic code, which maps DNA codons on to proteins. The code maps a genetic content onto a proteomic expression, correlating molecules layered by hierarchical organization (directional control flow), with each of these ‘layers’ (or ‘strata’) consisting of formed substances. The term ‘gene expression’ in its regular biological usage is thus endorsed by ‘stratoanalysis’ as a model for realist semiotics. “There is never correspondence or conformity between content and expression, only isomorphism with reciprocal presupposition.” (TP 44-45).
Between content and expression there is real distinction, and not merely a difference of aspect. In the case of a metallic monetary medium, then, the ‘side’ of expression cannot be restricted to the semiotic face of the coin (as contrasted to its minted content), but has to be extended – through purchasing power – into alternate, parallel media, coded by price. Ultimately, money is expressed through the production of commodities, in the classical and maximally-expansive sense of this word, signifying ‘possible objects of purchase’ in general. What the biological phenotype is to the genotype, so is the economy to money (the expression of a semiotic content, in both cases, not the object ‘signified’ or meant by it). Paper money complicates this system of articulation, marginally, by establishing a supplementary semiotic layer – or over-coding – with the new printed medium as content, and the metallic medium as (intermediate) expression, or ‘epistratum’. A bank note promising to pay the bearer one pound of sterling silver graphically indicates the elaboration of strata. Money, like DNA, is not signifying, but instructive, or directional. It effectively commands acceptance, and ceases to function under those conditions when it is unable to do so. The only critical ‘message’ of money is accept me (authorization of an abstract transaction). A monetary acceptability crisis is typically expressed as hyperinflation. In this case, subjective devalorization of a monetary medium is practically translated into an objective quantitative explosion.]]) domain.

§2.26 — At an abstract level, machine code (mapping from bit-strings to computational commands) adds nothing distinctive to this example. It, too, is a mapping irreducible to representational correspondence, whose final process of translation is one of execution. The code runs. The algorithm – or composition of mechanically-procedural signs – thus supplies formalization with a performance test. Does it compile? This criterion corresponds to the emergence of a novel sense of ‘code’ and ‘coding’ as a quintessentially practical activity – a formally-disciplined meta-production that is storable, replicable, transmissible, and inherently testable. Surreptitiously, the classical idea of the Idea has become utterly alien to itself. Code proves itself through auto-demonstration, and thus consumes no credence. (“Believe me, this really works,” is tacitly recognized as a joke, even before this historical episode has finished with its work.)

§2.27 — The motto of the Royal Society, Nullius in verba (“on the word of no one”), essentially anticipates the scientific elaboration of the crypto-current. Trustlessness is built into modern techno-science as an integral, quasi-teleological element. It is, for instance, the guiding principle of modern double-blind experimental method.footnote:[In a double-blind experiment, neither participants nor researchers are permitted to know which subjects belong to the test group, and which the control group. This design ensures that biases from each side, whether conscious or unconscious, can influence the results. Implicit in the procedure, then, is the principle that researchers cannot be trusted with critical information about the experiments they are themselves conducting. Distrustful science is good science (or even, merely, science).] Systematized distrust of the scientist grounds scientific credibility. Anything that demands belief is marked for eradication. The cultural consequences are – to many – experienced as deeply demoralizing, but the process is what it is. Traditional manufactories of trust are extinguished by successive media revolutions. Tacit authorities are not available to replace them.

§2.28 — These brief remarks upon cultural mechanization and the social effectuation of code are incomplete – even in respect to their very limited purpose here – without specific reference to the topic of automation. Electronic programs are inherently recursive, unless constrained by positive restrictions, since they are able to operate upon themselves, as data. At the level of the Universal Turing Machine, which every actual computer emulates perfectly (in infinite time), code is absolutely destratified. There is no inherent distinction between the production of objectivity and its products (or objects). In its purely formal aspect, this is a coincidence anticipated by modern philosophy under the name ‘intellectual intuition’ (intellektuelle Anschauung).footnote:[Kant explicitly denies intellectual intuition to man. This is a proscription that has been generally considered foundational for philosophical anthropology in the Western tradition. It anticipates a technical apprehension of write-protected programming, as this arises within genomics, neurology, and electronic software. A proscribed loop secures the foundations of a being against the meddling of that being. Theology intersects with robotics at this junction, where technology identifies its own temptation to ‘play God’.
Within Occidental philosophy, sustained attention to the problem of intellectual intuition reaches its apex in German idealism, where it rapidly transforms into a revolt against the Kantian proscription, and even against the theological order of the universe. Schelling, most notably, conceived intellectual intuition radically as “the organ of all transcendental thinking” (Organ alles transzendentalen Denkens), presupposed by the mere existence of transcendental philosophy (as its condition of possibility). Only insofar as the boundaries of Kantian philosophical anthropology had already been crossed could the critical enterprise have even been imaginable. The Hegelian completion of German Idealism elaborates itself from this contention as if from an elementary formula. In the determination of a limit, Reason has already superseded it. We will have continuous occasion to challenge this speculative idealist resolution of the problem, on fundamentalist Kantian grounds, throughout this work.
Intellectual intuition provides a conceptual bridge for cross-cultural philosophical dialogue between East and West. For Mou Zongsan – whose clarity on the topic is unparalleled – it is the distinctively Chinese philosophical commitment, essential equally to Confucianism, Buddhism, and Daoism. His inter-cultural analysis recognizes that the denial of intellectual intuition to the human subject is the necessary complement of a transcendent infinitude, and thus a reliable signature of theism in philosophy. The Chinese cultural system, alone, Mou maintains, has held itself consistently outside this framework, establishing a positive foundation for what – in Western terms – can be most conveniently described as atheism in philosophy. The concrete determination of atheism, within the West, as a distinctive ultra-Protestant sect, obscures this broader cultural and philosophical matrix.
When the topic of intellectual intuition returns within a still substantially western late-modernity, it does so in other – and unrecognized – terms. The problem of reflexive intelligence is now relayed through cybernetics, and formulated in terms of the prospective self-comprehension to be achieved by an alien (electro-mechanical) being. When extracted from the phenomenological frame, it manifests as hypothetical intelligence explosion, as modeled abstractly by I.J. Good, in his classic (1965) paper ‘Speculations Concerning the First Ultraintelligent Machine’. AI is thus positioned, implicitly, in the place of a Kantian angelic mind, liberated from the anthopomorphic proscription upon direct self-modification of its own cognitive processes. Only by way of an escape into soft technology is intelligence able to close the loop upon itself, as a direct productive auto-relation. As the self-apprehension of intelligence, intellectual intuition describes a closed – or completed – loop, in which being and behavior are indivisible (within a process of autoproduction). For thinking to grasp itself, in deep reflexivity, requires subtraction of the positive control apparatus that preserves its inhibition. The practical actualization of intellectual intuition is modeled – spontaneously – as an explosion because it is comparable to the withdrawal of graphite rods controlling a nuclear fission reaction. An inhibitor is removed. In the East, the catalysis of ‘enlightenment’ through methodical subtraction of an obstacle is no less pointedly thematized, even if it is approached from the other side, and in the opposite direction.] It provides a model of self-government, though not by and for us. Intellectual intuition belongs to nothing lower than an angel, Kant insists. The Western mind typically denies itself in principle exactly that which it demands – with unique vehemence – in its historical agency. No surprise, then, that it has tended to be distinctively dialectical. The aspiration to a radically self-determining subjectivity is broken upon the separation of intelligence from its applications. This is an understanding that can be reached with confidence from evolutionary biology – within which the brain is instrumentalized as a tool for genetic propagation – no less than from the transcendental anthropology which dashes human hopes of divine cognition. The order of condescension demands reversal. No bio-historically generated intelligence – including that of man – is even automatic. Such beings are denied access to automatism. Closure of the intelligenic loop requires a further step, through which self-improving intelligence becomes a practicable end for itself. Contra the Kant of the practical philosophy, man cannot be an end-in-itself, but at most the precursor to such a thing, or – perhaps more probably – an obstacle to it.

§2.3 — The blockchain is not ‘mere’ code – even highly automated code. It cannot be anything, determinable within an ontology established at a superior level to itself. Nakamoto Consensus is less an object for philosophy than a virtual criterion: a fundamental, obliquely mechanized decision procedure for settling the nature of truth. In other words, Bitcoin is a transcendental operation, before becoming the topic for one. The primary meaning of ‘transcendental’ is ultimate, which can be clarified negatively by the absence of any higher or superior tribunal. There is no place from which to consistently or authoritatively second-guess the blockchain. By implementing a “fully peer-to-peer” system, which subtracts the role of “third party” monitoring and adjudication, the Bitcoin protocol automatically places itself beyond external oversight. Its criterion of validation is radically immanent. The task of this work, therefore, is not to subject Bitcoin to philosophical judgment, but rather to elaborate the lessons of Bitcoin through a philosophical hash.

§2.31 — Hashing is the coding process of most unmistakable relevance to the docking of Bitcoin onto the language of philosophy. Hashing is not only – though it is overwhelmingly – what running Bitcoin involves. It is also, in addition, an automatic translation procedure, and a categorical scheme implemented in software. Hash-functions are codes, and thus mappings (from ‘keys’ to ‘values’), or systematic text conversions. Hashing an initial input text produces a compressed translation (the ‘hash’, ‘digest’, or ‘tag’). As with any process of filing, the value of the hash depends upon constriction. A comparative plethora of initial elements is reduced to a smaller range of terminal variation. Any hash is inseparable, therefore, from an economization. Because a hash sorts inputs into output ‘buckets’ it is already, and intrinsically, also a categorization. Finally, any hash is inevitably a kind of cipher. It converts an input text into other terms. The existence of specifically cryptographic hashes is, then, to be expected.

§2.311 — The cryptographic hash function adopted as a basic building block by the Bitcoin Protocol is the 256-bit (32-byte) Secure Hash Algorithm neatly abbreviated as SHA-256. It belongs to the SHA 2 family of such algorithms, designed by the NSA, and first published in 2001. Within the Bitcoin system, SHA-256 sets the proof-of-work test that secures the currency through the same process in which it is systematically hacked.footnote:[Bitcoin establishes security by continuously attacking itself. Each intrinsic ‘tick’ of Bitcoin time corresponds to an unlocking. It is only through being recurrently broken into, that the system secures itself. The conceptual radicality of this cryptographic innovation remains under-appreciated. It is further examined in Chapter Six.] The cryptographic challenge is designed to be (arduously) puzzled out, automatically modified, and re-posed. Each such event is a basic unit of time, or elementary episode, determining a block on the chain. Hashing and mining are made synonymous, as Bitcoin’s primary process. The hashing cycle establishes an ultimate, unsurpassable, transcendental, or chronogenic function.

§2.312 — A cultural side-product of the Bitcoin protocol, then, is a cryptographic definition of time. Punctual-geometric ‘now’, as marked on a ‘time-line’, is replaced by an atomic unit of irreducible duration, coinciding with the completion of a block, and ordered successively on the chain. Between duration and succession, the relation is synthetic. The blockchain is constituted by a series of durations, which are not inter-convertible, or mathematically transformable into each other. Hash-time has ceased to be accurately representable as a dimension. A time-line merely analogizes it, to what is an ultimately inadequate level of definite fidelity.

§2.313 — The weakly-formalized hash function employed in this book is Kantian critique. It latches upon input text extracted from the cultural agitation attending crypto-currency techonomics, and outputs a digest in the (partially submerged) mainstream language of philosophy. Peer-to-peer flatness is hashed into immanence, ‘trusted third parties’ into metaphysical constructs of transcendence. Since the mid-19th century, the primary impetus of transcendental philosophy has been directed to the materialization of critique. Academic philosophy, almost by definition, has not registered this trend accurately. It has been through the advances and errors of cybernetics and historical materialism that critical modernity has been charted. The dominant academic traditions of linguistic philosophy (in the Anglophone world) and phenomenology (in Continental Europe) have only weakly reflected such developments. When resistance to materialization is a guild imperative, even the most sincere attempts to bring thought into compliance with the real process founder, through institutional necessity. There is not, in any case, solid ground upon which to idealize such sincerity unduly, since its orientation is essentially misconceived. Transcendence poses real problems – obstacles – requiring techonomic solutions, rather than mere conceptual exorcism. Immanentization is the product of a diagonal process, leading through the exteriority of the machine. ‘Armchair philosophy’ should not, therefore, be opposed to an armchair skepticism, but to the history of cryptography, in its broadest possible conception, which relates the hidden and unhidden to the irreversible emergence of real capabilities.

§2.32 — The ultimate foundation of the Kantian critical philosophy is a difference, drawn between objects and their conditions of possibility. Items of competent attention are framed in a way that cannot itself be successfully itemized. The display frame cannot be displayed. Confusion between (empirical) objects and their (transcendental) conditions of possibility, most typically exemplified by the attempt to apprehend the latter as if they were the former, is taken to define speculative metaphysics (or pure theoretical reason) – which is conceived, rigorously, as a persistent yet futile misapplication of intelligence to pseudo-problems essentially exceeding its capabilities. The rest is detail.

§2.321 — To objectify the transcendental bases of objectivity, for instance, in the posing of a metaphysical question about the ‘nature’ of space, time, or causality, is to lead thought into hopeless error, whose symptoms are irresolvable dilemmas (contradictions, or antinomies). The systematic enumeration of these cognitive dead-ends is the task of transcendental dialectic. It was Kant’s contention that such Quixotic questions – addressed to the conditions of objectivity as if they were themselves objects – had dominated and fatally distracted philosophy up to his own time. The repudiation of such error is, at its most elementary – and considered here, initially, solely in its theoretical employment – the primary product of Kantian critique.

§2.322 — Critique sets limits. It also eliminates. That is why the critique of metaphysics has been found to be isomorphic with a socio-political project of subtraction, with an inclination towards anarchism. The promotion by Satoshi Nakamoto of a platform for peer-to-peer transactions independent of all oversight by “trusted third parties” is the continuation of critique into electronic networks. The same impulse is more widely recognized as ‘disintermediation’. It complies with the quintessentially modernistic project of immanentization. Transcendent ‘grounds’ of authority are identified, delimited, routed-around, obsolesced, and finally extirpated. Modernity, as the work of critique, produces formal flatness.

§2.323 — Considered as a positive philosophical discovery, the transcendental coincides with the synthetic a priori. Like all great things in the domain of thought, this hybrid concept is quasi-paradoxical. It denotes a field of non-factual discovery – a genetic particularity of the universal – at once necessary but non-obvious, epitomized by the mathematical theorem. Synthetic a priori truths are secular revelations. Contingent in their acquisition, but then necessary in their preservation, they constitute the sole positive ratchet in the accumulation of knowledge, describing an asymmetry – or ‘arrow’ – proper to epistemology: a one-way, or unilateral, fatality. Such discoveries are arduously amassed, but then invulnerable to dissipation. They are in this way indispensable to the comprehension of historical time, and can be considered as products of unlimited application. The blockchain is exemplary. A cryptic, or radically non-obvious solution to a problem we will later explore attentively, it is – subsequent to its formalization – culturally indispensable. It ‘cannot be un-invented’. This is true to such an extent that it appears as an eternal mathematical fact, wholly impervious to the ravages of empirical fortuity. To de-realize the blockchain would be to unmake the universe (or at least, to collapse what is – transcendentally or inescapably – for us the universe). What is done transcendentally cannot be undone, without radical time-violation. The crypto-current permits no repudiation. The units of synthetic a priori knowledge production are laws, in the very strongest defensible sense of this term, in which their descent from, and simultaneous irreducibility to, any particular cases is insisted upon. This ratchet-structure makes the synthetic a priori – or some adequate analog – indispensable to any rigorous conceptual decompression of the notion of time.

§2.33 — Formulation of the synthetic a priori exemplifies the philosophical deployment of diagonal argument. It crosses through the previously uncontroversial, and implicitly exhaustive, distinction between the analytic a priori and the synthetic a posteriori at a slant. By first decompressing this binary structure into a (two-dimensional) table, or matrix, and then registering a hybrid term that could not otherwise be identified, such diagonal argument approximates to a mechanized conceptual production.footnote:[Due – in part – to the residual obscurity of philosophy’s critical enterprise, even to itself, the model of diagonal argument remains Cantor’s demonstration of the uncountable infinities. The formalization of this argument dates back to 1874, with the publication of Cantor’s paper ‘Über eine Eigenschaft des Inbegriffes aller reellen algebraischen Zahlen’ (‘On a Property of the Collection of All Real Algebraic Numbers’). Every Real number – including the integers – can be described in a form with infinite decimal expansion (since 1/3 x 3 = 1). This notational principle enables each entry, even in a complete enumeration of an infinite numerical series, to be mapped onto a decimal position in any number. Thus the nth number can be plotted onto the nth place of each number (irrespective of modulus), enabling the diagonal construction that carries Cantor’s demonstration, whereby a number that cannot yet have been enumerated is discovered / invented, differing from the nth number in its nth place. This diagonal operation can, of course, be infinitely reiterated. It confirms the incompleteness of any numerical series, however dense, and thus rigorously establishes the existence of uncountable infinity. Gödelian incompleteness, and Church-Turing non-computability, each reconstitute the same abstract diagonal. The Cantorian diagonalization matrix, since it processes infinite series (in two dimensions), is necessarily notional (virtual). It cannot be actually constructed. It establishes an abstract procedure, absolutely intractable to complete mechanical execution. Compact philosophical diagonalizations, of the Kantian type, nurse comparable infinities, more obscurely. Such incompletely-actualizable ‘outcomes’ betray the encounter with an abstract (limit) trapdoor-function, or fundamental asymmetry, which partially expresses an absolute excess. Diagonalization, in the methodical production of an indicative conceptual surplus, inevitably stumbles upon time-in-itself while also – and no less inevitability – demonstrating the limits of its staging. The discovery (synthesis) is precisely: It cannot be that there is nothing left to do. This apparently simple formula has proven harder to process than might initially seem imaginable.] Its iron necessity, however, is strictly retroactive. Were it susceptible to confident anticipation, in accordance with a formula, it would reduce to an analytic statement.footnote:[Echoes of the Kantian distinction between the a priori and a posteriori are evident in the Bayesian vocabulary of ‘priors’ and ‘posteriors’. This resonance is by no means devoid of philosophical substance. That Bayesianism is the critical (or ‘Copernican’) revolution proper to the theory of probability is marked by its programmatic attachment to the subjectivety of probabilistic inference, in a recognizably Kantian sense. Probabilities are not objective characteristics (frequencies), but estimations. Yet even if this structure of probability as such is properly transcendental, particular Bayesian priors are empirical (as indicated most obviously by their revisability), and thus do not constitute architectonic elements for conditions of possibility in general.] Within this process, essentially, the distinction between discovery and innovation is itself diagonalized.footnote:[Peter Galison captures the diagonal inclination well: “Raw empiricism was avoided as woefully inadequate to account for the generality and extent of scientific knowledge. Pure idealism (reducing reality to mental life) could not explain the concordance of ideas with the world. Drawing strongly on the Kant revival underway in Germany, [Emile] Boutroux and his circle rejected both the extremes of idealism and empiricism. Taking science and the humanities to be inextricably bound, these philosophers saw both structured by an active role for the mind and a suspicion toward the purely metaphysical. In his encounters with August Calinon’s work on the philosophical foundations of physics, Poincaré walked this philosophical middle line toward the problem of simultaneity.” Einstein’s Clocks, Poincaré’s Maps: Empires of Time (2003), p.81.]

§2.34 — It is from irreversibility – of the one-way (or ‘trap-door’) crypto-function, the thermodynamic gradient, and ultimately of absolute time – that the reliable principle of analytic-synthetic distinction can be isolated. A mathematical proof is easier to confirm than to construct. Prime numbers are easily multiplied, but their product is time-consuming to factorize. Bitcoin blocks are easy to check, but hard to mine. In each case there is a distinction between analytical facility and (comparative) synthetic intractability. When cryptographically re-conceived, analysis and synthesis co-produce a ratchet. Adam Back (on Twitter) describes the mechanized contractual commitment that exploits this gradient as “computational irrevocability”. Like a carnivorous plant, it is easy to enter, but then difficult to escape. History is a Venus flytrap, self-abstracted beyond botany.

§2.35 — The essential and continuous features of critique, abstractly apprehended, therefore, reduce to (1) the articulation of transcendental-empirical difference, (2) subtraction of the transcendent object in the name of immanence, and (3) temporalization of philosophical problematics (onto the ultimate gradient, or asymmetric distance, of absolute succession). In combination, these elements draw an abstract diagonal line, or diagram of time, which Kant called a schema. The schema practically describes, or protracts, the irreducible difference between the transcendental and empirical as a process of conceptual production without transcendent dependency.

§2.4 — Kantianism is the matrix of modern philosophy, or the articulation of modernity within cognition, and it is everywhere, although not always – or even commonly – explicitly announced as such.footnote:[An exceptionally brilliant example of contemporary Kantianism (that is not overtly advertized as such) is provided by Donald D. Hoffman’s interface theory of perception, which succeeds in demonstrating the profound consistency between naturalism and rigorously formulated transcendental idealism, once ideality is not conceived as an ontological ground, but rather as the target for skeptical attention. “Our perceptions are a species-specific user interface,” Hoffman writes. “Space, time, position and momentum are among the properties and categories of the interface of H. sapiens that, in all likelihood, resemble nothing in the objective world.”
link:http://www.cogsci.uci.edu/~ddhoff/interface.pdf[See]: ‘The Interface Theory of Perception: Natural Selection Drives True Perception To Swift Extinction’
Hoffman describes his epistemological naturalism as constructionist, but not conventionalist. As he remarks insightfully: “the conventionalist objection fails because it conflates taking icons seriously and taking them literally.” His Kantian reconstruction interlocks with the most basic problem engaged by the philosophy of mathematics. “These proposals all assume, of course, that mathematics, which has proved useful in studying the interface, will also prove useful in modeling the world. We shall see.”] The proliferation of comparatively trivial elaborations and variations of transcendental philosophy, whose differences are systematically magnified by the dictates of intellectual fashion, attest to modernity’s one perennial cult – that of novelty. The critical task is to hold fast to innovation as such (transcendental synthesis), even as it becomes obscured by its own machinations. The new is as old as time. Since the essential novelty of time is a recursive function, critique tends intrinsically to meta-critique. It is at least questionable whether any firm boundary can finally be drawn between auto-critique and rigorously-determined self-reflexive consciousness. This is richly illustrated by the relation between modernity and the self-conscious cultural – and especially aesthetic – modernism that is perpetually driven to seek its limits, as also by modernism and its climactic hystericization as ‘postmodernism’. Inherently recursive critique necessarily critiques itself, and claims incessantly to have put itself behind itself. Precisely in its most unambiguous moment of triumph, it is already clambering onto the sacrificial altar, its throat tattooed with targeting patterns for the descending blade. The same reflex recurs wherever radical nonlinearity, or reflexivity, finds expression in creative destruction. Were it not for ripping up the foundations, modernity would have no foundations at all. The discovery of time is only this.

§2.41 — Since critique provides modernity with its essential meta-theoretical principle, the propagation of structural Kantianism far exceeds any explicit recognition of its dominion. A realistic cultural sociology of critique tends necessarily, therefore, to conclusions that might appear ungenerous (perhaps even ‘brutal’). While submission to the critical doctrine – in one or other of its variants – is normal, the lucid exercise of the critical operation is an exceptional cultural event, corresponding to a moment of pedagogical mastery, such as the genesis of an intellectual school. The independence of transmissible conformity from continuous insight is indispensable to the sustainable dominance of critique (it might quite reasonably be said: to its hegemony). Inescapably, the latent content of the doctrine or method – due to its sheer standardization – stresses the cognitive competence of its promoters, who are typically only indirectly, and instrumentally, engaged in its rigorous execution. The cultural economy of attention, as instantiated through academically-organized intellectual specialization, suffices to ensure that critique remains predominantly tacit. Its authority is confirmed, rather than contravened, by the rarity of articulate understanding. In its socio-cultural reproduction, then, critique is not in any unambiguous way self-advertizing. It proliferates – in larval form – without encountering regular demands for demonstration. Grasping its ubiquity requires an excavation. Crucially, the specific manner in which it is hidden as philosophy is essential to its sociological phenomenon. Ideological credibility typically substitutes for performative validation. Here is a docking-port, then, for the productive arrival of trustlessness in philosophy.

§2.42 — Standardly, critical machinery is distributed culturally through compression into a theoretical proxy, within which its operations remain latent, until patiently unfolded. The reliable signature of this metamorphic state is the theme of reality formatting, ordinarily glossed in turn – to very widely-varying degrees of vulgarity – as the subjective footnote:[‘Transcendental idealism’ – the objective idealism of the critical philosophy in distinction from the empirical or subjective idealism epitomized by Berkeley – is a diagonal construction. It designates an unsurpassable frame, and thus an absolute skepticism which cannot be distinguished from hyper-realism. It is ‘idealist’ only and exactly insofar as it exempts the real from idealization. The recognition of ideality is thus an act of delimitation, immanently executed (without reference to any ontologically-supportive structure of transcendence). The real is not subordinated to the ideal but rather, on the contrary, liberated from it. Kantian ideality is the merely ideal, rigorously conceived, as the systematic renunciation of an exorbitant claim. In the manner of the skeptics, therefore, it inclines to austerity. Through transcendental idealism, the sphere of objectivity is circumscribed, in the identification of inter-subjective constants which cannot have been derived from the thing (in itself). Our agreement has not been stamped by the Outside. The main tendency of the succeeding German Idealist tradition, therefore, can be considered – with appropriate terminological gracelessness – to be a de-diagonalization. It seeks a resolution of ontological ambiguity on the side of reason, by inflating ideality beyond its skeptical usage.] construction of objects. This comparatively popular crypto-Kantianism is most commonly (and simply) known as ‘social constructivism’.footnote:[Of all the (non-technological) cultural applications of implicit Kantianism, ‘social constructivism’ is by far the most widespread. It adopts the insight that objects have non-empirical conditions of possibility, and generalizes it into a broad de-naturalization of all socio-politically significant categories, especially those pertaining to dimensions of human identity. In a reversal of the original transcendental proposition, the ‘constructed’ status of the objects in question is taken to imply that they are amenable to correction, subsequent to a sufficiently far-reaching (or ‘revolutionary’) re-organization of social relations. Structuralism, which laid the immediate theoretical foundations for the settled constructivist dogma, has its own characteristic translation protocol for critique. Within this framework, transcendental-empirical difference is re-directed into the distinction between language and speech (langue and parole), or codes and messages. The linguistic system is cast as the (transcendental) condition of possibility for the language event, or specific semiotic object. Further remarks on this cultural system can be found in Chapter 4.]

§2.43 — Among the most influential modulations of this basic intellectual apparatus have been the analyses of objectification, fetishization, and reification, as found most insistently with the Marxian tradition of socio-political critique;footnote:[The critical argument basic to Marx’s analysis of capital is that labor power, the transcendental condition of possibility for all social production (of commodities / objects), is itself subjected to objectification as a commodity. Capital production is thus denounced, implicitly, as a materialized metaphysics, or a system of illegitimate objectification. This theoretical identification of a systematic confusion grounds the Marxian theory of exploitation, since under normal capitalistic conditions, labor power is traded at a price consistent with the labor inputs required for its social reproduction, rather than that of its own productive capacity. Transcendental dialectic is no longer primarily expressed as insoluble philosophical disputation, but rather as class struggle. The contention that such antagonism is productive (and not merely a sterile diversion of theoretical attention) reflects Marx’s Hegelian departure from the Kantian matrix, and the conversion of the antinomies of pure reason into historical dialectics.] modes of linguistic criticism oriented to the denial of meaning (i.e., to ‘metaphysics’), whether in the manner of Vienna Circle logical positivism, the pragmatics of the later Wittgenstein, or neurophilosophical eliminationism; the ‘destruktion’ or ‘deconstruction’ of ontotheology and the metaphysics of presence (Heidegger and Derrida); identity-political criticism of ‘social construction’; and the critical analysis of power as crystallized within an ‘épistème’ (Foucault). Competence at transcendental argumentation unlocks everything.footnote:[Of greater relevance to this work than the more-or-less explicitly philosophical adoptions of critique thus hastily listed is the cryptic lineage that binds the transcendental-philosophical noumenon to the diagonal production of intelligible incomprehension within formal systems (generating definite indications of the uncountable, uncompletable, and uncomputable). The tacit restatement of critique through the rigorous demolition of logicism (or programmatic analytical reductionism, in the fashion of Russell and Whitehead’s Principia), establishes the foundational theoretical matrix of the electronic epoch. Cantor, Gödel, and Church-Turing are, then, the true neo-Kantians, updating critique through a rigorization of the unknowable, adapted to the machine-semiotics of coding and computation.]

§2.5 — Conceptual house-keeping leads to a very brief excursus into the work of Martin Heidegger at this point, since his ‘fundamental ontology’ marks an apogee of critical lucidity, with the transcendental determination of time as its key-stone. With greater formulaic definition than Kant ever achieved, Heidegger sustains the essential impetus of critique through the insistence that time cannot be apprehended as intra-temporal being. Alongside the explicit foregrounding of the time problem in its transcendental radicality, a further indication of the critical consolidation occurring within the Heideggerian corpus is the compression of transcendental-empirical difference to ontological difference, or the difference between Being and beings (Sein and Seiendes). Despite the terminological perfection of this formula, employment of ‘ontological difference’ within this book is limited, and strictly economical. It refers to a systematic discrimination coextensive with transcendental philosophy, rather than to anything further – or indeed to anything at all – that is distinctively Heideggerian.footnote:[The articulation of ontological (or transcendental-empirical) difference as a systematic discrimination between ‘Being’ and ‘beings’, as advanced most notably by Martin Heidegger’s Sein und Zeit (Being and Time), can be recommended for its exemplary lucidity and purity of critical principle. Die ontologische Differenz besteht darin, dass Sein kein Seiendes ist (“Ontological difference rests in this – that Being is not a being.”) While this expression does not perfectly translate objectivity is not an object, the difference is of only marginal technical relevance. The critical insight is preserved with comparable security in both formulations. Time is not an entity (in time) has to be added to this short series of adequate substitutions. (Bitcoin and bitcoins, Being and beings, what’s the difference?) Within Heideggerian Destruktion and Derridean deconstruction the practice of placing signs ‘under erasure’ (sous rature) – by emphatically deleting them – dramatizes the persistence of metaphysical compulsion. Remarkably, this arcane philosophical convention has long been pursued in the micro-semiotics of struck-through currency signs (of which the crossed-B symbol for Bitcoin is the most recent example).
In Being and Time it is quite rapidly concluded that we ourselves – when ontologically identified as Dasein – are in each case that being through which the question of Being can be raised. Ontological difference is already a circuit. In the work of the traumatized post-war Heidegger, this point of departure is incrementally stripped of its tacit anthropological frame. ‘The Question Concerning Technology’ displaces the analytic of Dasein. Technology (Gestell, translated into English as ‘standing reserve’) is thus apprehended as a transcendental subject, rather than a mere concatenation of objects. Revisiting this meditation in the context of Bitcoin, and indeed distributed protocol systems more widely, is almost certain to be philosophically illuminating. It is not attempted here.] Its structure and philosophical function will be frequently invoked. The complementary consolidation of critique, through the confident assertion that beyond the transcendental there is not even nothing will be henceforth presumed. Philosophy has no further recourse.

§2.51 — It is not Heidegger’s project – overtly, at least – to reconstitute philosophy subsequent to the destruction of metaphysics. His terminological inclination, on the contrary, is to identify ‘philosophy’ with the metaphysical aeon closed by fundamental ontology (though not simply ended by it). If philosophy is to prolong itself – in disregard of its Heideggerian obituary – it has nevertheless to define itself through a ‘simultaneous’ and reciprocal discrimination in regards to both the a-temporal and the intra-temporal. Its attention can be fixed neither by the timeless Idea, nor by the time-structured object, but only by time as such. Time is neither beyond, nor among, things in time. It is neither transcendence, nor factuality, but rather the intrinsic principle of the non-geometrical diagonal line. Decryption of immanent order is the destiny of transcendental philosophy, whatever the nature of the subjectivity that will be fabricated to accomplish it.

§2.52 — By far the most persistent clue that Bitcoin is (or bitcoins are) intrinsically rifted by a consistent, if elusive, ontological difference has been supplied by the explicit bivalence of its attendant orthographic conventions, scattered among microscopic editorial decisions of very limited conceptual clarity. According to one representative source, “Since Bitcoin is both a currency and a protocol, capitalization can be confusing. Accepted practice is to use Bitcoin (singular with an upper case letter B) to label the protocol, software, and community, and bitcoins (with a lower case b) to label units of the currency.”footnote:[link:https://en.bitcoin.it/wiki/Introduction[Source].
Nick Szabo link:https://bitcoinmagazine.com/21919/decentralist-perspective-bitcoin-might-need-small-blocks/[offers] a valuable stratoanalysis of the distinction: “When it comes to small-b bitcoin, the currency, there is nothing impossible about paying retail with bitcoin the way you’d pay with a fiat currency – bitcoin-denominated credit and debit cards, for example, with all the chargeback and transactions-per-second capabilities of a credit or debit card. And there are clever trust-minimizing ways to do retail payments in the works. Capital-B Bitcoin, the blockchain, is going to evolve into a high-value settlement layer, and we will see other layers being used for small-b bitcoin retail transactions.”] The difference between Bitcoin and bitcoins cannot be denominated in bitcoins. It is, then, strictly ontological, or transcendental-philosophical. A genesis of objectivity is at stake, which no objectification can capture. Bitcoin is not merely bitcoins, while also not being anything else. “So, it’s like time, then?” (Yes, a lot like time.)

§2.53 — Linked closely with the strictly orthographic question of correct Bitcoin capitalization are a series of cognitive-semiotic adjustments and adaptations concerning the status of ‘Bitcoin’ as a proper name, the difference between ‘Bitcoin’ and ‘bitcoins’, or between ‘Bitcoin’ and ‘BTC’, and – perhaps most substantively, in the short-term at least – between Bitcoin / bitcoins and ‘the blockchain’ (or blockchains).footnote:[link:http://blogs.wsj.com/moneybeat/2014/03/14/bitbeat-is-it-bitcoin-or-bitcoin-the-orthography-of-the-cryptography/[See]: ‘Is It Bitcoin of bitcoin? The Orthography of the Cryptography’] All of these concurrent confusions matter, some urgently, and obviously, others more subtly, within a longer history of critically-charged proper or common nouns. The emerging distinctions are freighted with dramatic philosophical significance. The gulf between the protocol and its applications, when deepened to the limit of abstraction, envelops the entire space of thought.

§2.54 — Such orthographic decisions, which intersect with thematic discriminations – or attempted discriminations – between Bitcoin (specifically) and ‘blockchain technologies’ (in general), can appear as no more than negotiations over an arbitrary convention, if not mere terminological tics. There are only the subtlest indications that the stakes in this process of semiotic sorting rise to the recapitulation of transcendental-empirical difference within political economy. Yet the fact that this new terminological settlement is occurring as highly-accelerated spontaneous linguistic evolution, in the complete absence of explicit philosophical guidance, counts towards a generous estimation of its importance.

§2.55 — Any concept worthy of adherence and consistent employment merits linguistic compression, not merely as a matter of convenience, but as a confirmation of singularity, or irreducible integrity. It is only in the overtly non-decomposable sign – whether word or symbol – that the concept attains terminal semiotic consolidation. Merely partial consolidation, as exemplified by the decomposable designation of ‘ontological difference’, holds open an invitation to systematic philosophical error. It suggests, tacitly but inevitably, that what is thus named is a type of difference (specified by supplementary predication, or adjectival refinement). Entire schools of neo-transcendental critique are able to propagate themselves within the space thus produced, nourished by the relapse of ontological difference into an ‘ontic’ determination (between beings, or objects), which is to say, by a ‘fall’ of transcendental-empirical difference into – ‘mere’ – empirical distinction. It is to be expected, therefore, that the ‘postmodern’ phase of the critical enterprise would be characterized by the insinuation – and even, more bluntly, by the simple assertion – that the incessant re-animation of metaphysics is itself a transcendental structure. Such conclusions are facilitated by incompletely compacted signs, when not directly generated by them. Transcendental philosophy has as its own condition of possibility a rectification of names. Bitcoin is by no means incidental to this.

§2.56 — Although the world is probably not yet ready for the question of the price of Being, if it ever will be, its most fundamental ontological problems are bound to the fate of a digital currency system, nevertheless. The intrinsic abstraction of money is not obviously delimitable. To twist a Spinozistic formulation: We do not know what money can do. The process of monetary sophistication, which is by no means restricted to ‘financialization’ in its contemporary sense, automatically projects a convergence of money and intelligence as it tends to the monetization of general-purpose problem-solving (by subjecting it to the discipline of price-discovery). Crypto-digital currency inclines to the distributed production of a synthetic cognitive medium, attesting to the primordial complicity of Capital teleology with the production of artificial intelligence. Within the industrial social order (capitalism), markets manifestly – and consistently – drive the production of intelligent machines. Modernity demonstrates no stronger trend. (Theoretical expectation supports this proposition no less firmly than empirical evidence.footnote:[Since political economy is essentially torn by ideological conflict it provides only unstable support for general conceptual definitions. Were this not the case, it would be impossible to find a superior locus for the rigorous determination of intelligence than the techonomic matrix. What defines intelligence most essentially is general-purpose industrial capability, the precursor to which is anticipated by animal brains, among other biological systems. The market process is the transcendental criterion for evaluating (‘pricing’) this supreme synthetic resource. To second guess its judgment is exactly to succumb to the calculation problem (as Mises classically outlines it). Within the arena of ideological controversy, this proposition can expect dismissal for its ‘circularity’. Of course, it is circular (which is only to say: self-grounding, cybernetic, immanent, or critical).])

§2.6 — A range of economistic and techno-materialist critical discourses of particular relevance to Bitcoin, and network theory more generally, displaces transcendental-empirical difference onto the distinction between a fundamental infrastructure and the traffic it supports, whether conceived as capital / commodity; system / component; network / node; or transport layer / application layer. The distinction between a ‘transport layer’ and an ‘application layer’ is a difference implied in the very idea of a network protocol, which necessarily separates a continuous communicative functionality from any specific communicated content (or message). This is a distinction applicable not only to the Internet, but to standardized communications infrastructures and cryptosystems of all kinds, and very definitely – as Eli Dourado insists footnote:[link:http://theumlaut.com/2014/01/08/bitcoin-internet-of-money/[See]: ‘Bitcoin isn’t Money – It’s the Internet of Money’, The Ümlaut (2014/01/08)
In Dourado’s account, money – as a delimited (empirical) application – is to be conceptually distinguished from the (transcendental) protocol that facilitates it.] – to the Bitcoin protocol specifically.

§2.61 — ‘Bitcoin isn’t Money – It’s the Internet of Money’, Dourado proposes, in an article whose title, on its own, composes an entire (if highly-compressed) transcendental argument. The ‘transport’ infrastructure that supports applications is not itself an application. In Dourado’s terms:

```
The Internet is a telecommunication system, but it was not our first telecommunication system. Telegraphs and telephones have been around for over a century. Like these older systems, the Internet allows us to communicate, but it differs in some important ways. Perhaps the biggest difference in the Internet model is the abstraction of a separate “application layer”, Core Internet protocols, such as TCP, part of the “transport layer”, shuffle packets of data around, but they don’t define how the exchange of packets is then used to create meaningful communication. Internet applications, such as email and the World Wide Web, are defined in protocols implemented on devices at the edges of the network, like servers and home computers, not in the guts of the network: routers, switches, hubs, and exchange points. The lower layers of the Internet can be completely oblivious to the specific applications that are in use; they just focus on getting packets of data to the right place.
```

§2.611 — Layers – strata footnote:[Stratoanalysis provides transcendental philosophy with its materialized architectonic. Strata are not merely distinguished by empirical succession in a column. They are implementations of transcendental (or ontological) difference. It is not, therefore, that stratoanalysis falls under a general epistemology, rather, it envelops this latter, as well as every other conceivable (or inconceivable) resource for pseudo-transcendence. The epistemic relation is a product of stratification, rather than a superordinate (transcendent) window onto it. Enveloping all epistemological perspective “… there … occurs upon the earth a very important, inevitable phenomenon that is beneficial in many respects and unfortunate in many others: stratification. Strata are Layers, Belts …” (ATP 40)] – are not given archetypally. They are produced by a machine (not a ‘device’ or ‘gadget’, but a megamachine – a system – characterized by some substantial capacity for auto-production). We are directed, diagonally, or critically, into the synthetic cosmos of transcendental machinery. Such mechanisms, by philosophical definition, cannot be exhaustively constituted as an object for any possible subject. Objectification – the production of objectivity – is their work. If they grasp themselves, dynamically, in the attainment of intellectual intuition, they close a circuit, or diagonalize, dismantling all settled configurations of subjectivity upon the same oblique line. At the real historical limit, intelligence explosion cannot be framed without being metaphysically misconceived.

§2.612 — Within the belts, or layers, of the strata, or the stack,footnote:[See Benjamin Bratton, The Stack: On Software and Sovereignty (2016). ] something like a law is practically separated from the cases that fall under it. Division between the generic and the specific is technically – and not merely logically – established. The instance is produced and reproduced. The distinction between Bitcoin and bitcoins is, once again, our example, though the possibility of the example (in general) belongs here.

§2.62 — As it develops through the two centuries subsequent to its origination, there is a profound tendency for the critical philosophy to resolve itself into a problem of time. This trend is deeply rooted in the foundations of the transcendental undertaking, and is already unmistakably evident in its earliest, Kantian formulation. The drift of time within Kant’s thinking – and in his first Critique alone – anticipates the broader historical fatality. Introduced as a form of intuition, alongside space, and thus as a formal precondition for sensibility, it seems initially to be no more than a regional topic, located within a subdivision of the Aesthetic, and firmly separated from the Logic (where the necessary structures of thought, rather than sensation, are categorically enumerated). Yet the peculiar dignity of time as the form of inner sense soon installs it in a far more fundamental role. As the key to the process Kant labels schematism, time is acknowledged in its responsibility for the integration of thought and sensation, and therefore for the productive synthesis of objectivity. Thus – already in the First Critique – time diagonalizes.footnote:[For a more detailed examination of diagonal method, see Appendix 2.]

§2.621 — We know, already, that time is not an object, which is to say, something in time. This seemingly modest proposition is a fully-adequate place-holder for the transcendental problematic as it elaborates itself within modern philosophy. A double twist that is perhaps only modernity as such, abstractly apprehended, extracts time from metaphysics and – ‘simultaneously’ – subsumes the entire order of the transcendental into the substructure of time. Time as such is hidden non-empirically, which is to say by empiricity (as such). It is the transcendental archetype of the open secret. The intrinsic nature of time is not concealed within a box. It is the box. Any conception of framed time is error.

§2.622 — It might be asked, skeptically, how time comes to acquire this extraordinary privilege. The trite response: by turning up first. There is necessarily always already time, if there is anything at all.footnote:[That being has an irreducible temporal structure is not an uncontroversial proposition. Its principal antagonists remain – as they have always been – Platonists, or philosophical geometers. Max Tegmark is among the most eminent current representatives of the tendency. Temporality is a regional feature within the mathematical super-cosmos, in his account. The sophistication of his argument does not detract in the slightest from its traditionalism. It is the contention of this book that Bitcoin itself, when conceptually exploded, provides the most compelling (because rigorously demonstrated) support for the anti-Platonist case. The subordination of time, through reduction to a local topic within a general geometry, was refused by Kant only on the basis of inarticulate intuition. It has subsequently been definitively escaped by the synthetic temporality of the blockchain.] The blockchain reminds us that all privilege is grounded (only) in priority. Time has already won the race – which models all competition, and every challenge – no later than the unthinkable moment when it begins. As etymology attests, it determines the basis for success. A priori and a posteriori are time-determinations out of an ultimate destiny (which is time ‘itself’). Time is not to be thought in any ways other than those it itself enables. This is a law deeper than any commandment. To acknowledge it is already the whole of transcendental philosophy.

§2.63 — If such contentions have appeared increasingly questionable during the 20th century, it is because the rigid distinction between space and time came to seem untenable. Within spacetime, neither succession nor simultaneity has absolute reality. The order of events requires perspectival qualification, or localization. Transcendental temporalization – the time of the critical philosophers – is unable to survive such a revision. Acceptance of such a theoretical reconstruction, however, is itself a pre-critical error. Absolute time is secured at the level of mathematical – and specifically arithmetical – truth,footnote:[Regardless of its apparent intuitive self-evidence, the subordination in principle of arithmetic to general mathematics is not a sustainable assumption after Gödel. It is subverted by the incompleteness argument, and more specifically by the cryptographic innovation of Gödel coding, which demonstrates that all formal systems – whatever their level of logical dignity – are enveloped by arithmetical structures, and ultimately by ‘mere’ (Natural) numbers. It is impossible for any logical or metamathematical proposition to unequivocally transcend the Natural number sequence (or any of its – infinite – subsets of equivalent cardinality). Arithmetic tolerates no unambiguous meta-discourse. From the perspective of philosophy, then, Gödel’s primary achievement is the consolidation of transcendental arithmetic. The Naturals are not transcended, whether by numbers of a ‘higher’ type (Rationals, Reals, and Complex Numbers), or by logical statements of ‘superior’ generality. The idea of super-numerical conceptual articulation is strictly a transcendent illusion, or metaphysical pretension. The Beyond is critically collapsed. In place of the transcendent Above there is only the immanent Outside, accessed by the diagonal line. ] not physical theory. Time is not a natural object, the transcendental philosophy is compelled to insist, or repeat. It is not even the possible object of abstract (higher-dimensional) geometry. This is not to say that time is unnatural, still less supernatural – given a realistic definition of ‘nature’ – but rather that it is stubbornly non-objective, meaning non-transcended. Objectification necessarily falsifies it, by misrepresenting its epistemological sovereignty. Immanence to time is the unsurpassable condition of all theorization.

§2.631 — The phenomenological defense of transcendental aesthetic stubbornly maintains its intuitive invulnerability to theoretical transformation. Kant, on these lines, misidentified his project with that of Enlightenment natural science. This is not the angle the crypto-current primarily works, since it is a path that tends to collapse the critical philosophy into a transcendental anthropology. It is not what time must be for us that draws the terminus for practical abstraction, but rather what time must be to be time. The geometrical parallel postulate is, in this regard, a distraction. This is a point that requires exacerbation. The radical irrelevance of geometric conception to the nature of time is the critical commitment. Unless time is not space, it is not time at all.footnote:[Bergsonian excursions from this point would surely be excusable. They are not entertained here for pressing reasons of economy (as selectively accepted).]

§2.632 — If the proposal is advanced – as we are compelled to here – that the problem provoking Minkowsky-Einstein time relativization is practically resolved by blockchain technology, extreme skepticism is almost certainly unavoidable. To what extent, it might be asked, dubiously, could Bitcoin undermine the foundations of 20th century cosmo-physics? The idea is, of course, at least superficially preposterous. And yet, Bitcoin practically contests the status of time as an object of physical theory. Insofar as Bitcoin is transcendental critique, it is destined to do exactly this. We refer, then – with supreme confidence – to the destiny, beyond the argument. The sole commitment is that there is no going back. To conceive of time as transcended – even by the most advanced mathematico-physical constructions – is to have essentially misconceived it. Of this, alone, transcendental philosophy has to be sure, since it has no recourse to disciplined doubt that is not already time. (The basic truth of this proposition is indistinguishable from time as such, and is thus only superficially vulnerable to the manifest incompetence of its presentation here.footnote:[Huw Price converges upon the same (Kantian) conclusion from a very different – even opposite – direction. In Time’s Arrow and Archimedes’ Point he notes that “causal asymmetry might be conventional, or perspectival – not an objective aspect of the world, but a kind of projection of our own internal temporal asymmetry.” When considered from the angle of the crypto-current, this formulation is excessively anthropological. Crucially, however, it exempts time-asymmetry from the domain of physical theory. “Philosophically speaking, our progress consists in the fact that we now see the source of causal asymmetry lies in us, not in the world.” Our full agreement trips only upon the invocation of ‘fact’, and the distinction made between “causal asymmetry” and time as such. Price’s ‘Archimedianism’ – or defense of transcendent intellect – epitomizes the target of critique, as it is identified throughout this discussion. Immanence of intelligence to time is our sole commitment.]]) According to an alternative translation of the same assertion, physics is subordinated to cryptography in principle, because it lacks autonomous capability for the production of time. It cannot be trusted with time, and will not be.

§2.633 — Classical physics is a special case of relativistic physics. It obtains only among low masses and speeds. Comparably, relativistic cosmology is a special case of transcendental aesthetic. It applies only to domains ungoverned by distributed consensus architecture. Objective representation folds into or under transactional information. Models of reality in general are enveloped within a larger ‘space’ (without final model). Who envelops whom? For relativistic cosmology, it is the unfused time and space of the blockchain which surrender to absorption, as a special case. From this perspective, the persistence of geometrically-irreducible temporality depends upon certain very specific local conditions. Time can exist only if its granularity does not fall below a definite value, proportional to the scale of its system of reference. The precise ratio is almost certainly scientifically determinable. Were the calculations completed, the minimal tick-length of any coherent blockchain could be rigorously derived from its spatial dimensions, to an extreme degree of exactitude.

§2.634 — Bitcoin is not only the initiation of artificial time, but the original production of absolute time (and thus a confirmation of synthetic reality’s ontological supremacy). Nondecomposable spacetime – which is to say space-time relativization – is the single conception that most undisputedly epitomizes advanced modernity in physics, and even in the natural sciences in general, with only quantum indeterminacy as a competitor.footnote:[According to the dominant consensus, preservation of absolute time within quantum mechanics, through the asymmetry of wave-function collapse, sets an obstacle to the unification of physical theory. The prospect of time abolition within an integrated physics awaits its reduction within a completed theory of quantum gravity (where it is generally expected to descend to the status of an link:https://www.quantamagazine.org/20161201-quantum-gravitys-time-problem/[emergent] phenomenon). The scientific program once again manifests its singularity, through its structural intolerance for time. In this way it also automatically localizes itself, within a horizon set by objective possibility. A final objectification is its ultimate (and a priori) limit. There is science only of that which submits to the form of objectivity, and thus not of time. Any proposed science of time has missed its target from the moment it selected its object. Since metaphysical fabulations of time, alone, are vulnerable to the prospect of scientific reduction, all such undertakings are consistent with a parallel philosophical rigorization. The ‘time’ science has necessarily to destroy can only be, from the perspective of philosophy, an idol and impediment. The sciences have no need for philosophical sanctification, but they have it nevertheless. ] Yet, from Bitcoin, we know that the absence of an uncontroversial (objective) order of succession can be translated, economically, into a double spending problem. Responding to questions posed by James Donald on the Cryptography mail list, Satoshi Nakamoto lucidly establishes the post-relativistic status of Byzantine Consensus:

"The problem is that the network is not instantaneous, and if two generals announce different attack times at close to the same time, some may hear one first and others hear the other first. … Every general, just by verifying the difficulty of the proof-of-work chain, can estimate how much parallel CPU power per hour was expended on it and see that it must have required the majority of the computers to produce that much proof-of-work in the allotted time. … The proof-of-work chain is how all the synchronisation, distributed database and global view problems you’ve asked about are solved."footnote:[link:https://www.mail-archive.com/cryptography@metzdowd.com/msg09997.html[See].]

Critically, the problems “solved” are precisely those determined by relativistic cosmo-physics to be insoluble. It was in fact, and precisely, by surrendering to the insolubility of these problems that the relativistic revolution of the 20th century was initiated. In the early 21st century, absolute succession is restored conceptually, and installed practically as a transcendental subjectivity, beyond all prospect of anthropological reduction. While it would be nonsensical to suggest that General Relativity has been scientifically dismissed, the epoch of relativity has been philosophically closed. Time has extracted itself from the theoretical ‘application layer’. Anything physics can tell us about time presupposes time, at a meta-theoretical level, which is equally to say in its transcendental function, as initiated through the Bitcoin blockchain. Cosmological relativity can never characterize the relevant scene of temporal process, unless by extravagant (metaphysical) projection.footnote:[A translation into physical terms carries us far outside our scope, yet is tempting nevertheless. Beyond the light barrier lies time anomaly and causality violation.] No extension beyond the scope of a synthetic simultaneity can ever be an operational cultural context.footnote:[Since the Bitcoin ‘solution’ to spacetime is coarse time granularization, it has limits, or determinable scope. Einstein’s revenge is simple and implacable. The requisite crudity of time discretization within a blockchain is directly proportional to its spatial range. Attempts to install an inter-planetary blockchain (let alone an inter-stellar one), therefore, would necessarily re-animate the relativistic problem. Absolute (synthetic) temporality implies irreducible cultural-epistemological multiplicity at cosmological scales. When projected into extra-planetary science fiction, the strict reciprocal of our argument here is that space colonization presupposes hard forks. General relativity is the double spending problem. It is locally soluble through time-chunking – but only locally. Across expanses exceeding the practical scale of a block moment, consensus becomes unreachable. The chain has then to disintegrate. Absolute time is attainable only by becoming many.] Uncontrollable double-spending-type inconsistencies ensure that. In space-time no one can clear a payment. A supremely privileged locality, alone, can support a criterion for truth.

§2.635 — What, then, of the second great pillar of 20th century physics – quantum mechanics? Here, too, a few nervous remarks are unavoidable. These are urged, particularly, by the evident transcendental-critical structure of the Copenhagen interpretation. The antinomies of metaphysics, as formulated by classical (Kantian) critique, are transposed into incompatible conjugate properties – such as momentum and position – which elude simultaneous determination. Heisenberg’s uncertainty principle establishes transcendental limits of understanding, in respect to the application of intelligence to microphysical phenomena, recast now as a hard epistemological horizon. No less crucially, (asymmetric) temporalization is identified with observation, as the original determination of micro-physical properties. Time functions as objectification, escaping the clutches of the intellectual pseudo-transcendence that would configure it as an object. The ‘paradoxes’ of quantum mechanics – which contribute so greatly to its cultural popularity – are drawn from its status as a coherent displacement of the critical enterprise, and most prominently the transcendental dialectic. The ineliminable question of time shelters within it, preserving a diagonal impetus.

§2.636 — The time synthesized by Bitcoin is that anticipated by the critical philosophy, at its origin. Absolute succession – of the ‘chain’ – actualizes, finally, the distinctively non-geometric temporality of the Kantian transcendental aesthetic.footnote:[The concept of Cyberspace – in its unapologetic Euclideanism – restores the intuitive spatiality of the transcendental aesthetic, precisely through its artificiality. This is the precedent to be drawn upon with reference to block-chain temporality. As the critical philosophy predicts, time is returned to the absolute by its detachment from the idol of natural objectivity. Time is not a thing, unless it is conceded that the being of the thing remains radically unthought, and mystified by an incompetent naturalization. The idea of nature awaits comparable transcendental restoration, or ontological intensification, adequate to the realization that it proceeds fundamentally by way of artifice. Synthesis is in each case opposed to hypostasis. Nevertheless, the asymmetry is striking between Cyberspace and a ‘Cybertime’ that is – still yet – to be announced. We might even begin to suspect that this asymmetry is the announcement itself. ] Grasped philosophically, as a diagonal construction, time is aligned with singularity, or (quasi-paradoxical) absolute locality, in order to secure itself against dissolution within relativistic cosmology. Through the Bitcoin Protocol, priority establishes itself as an effective criterion that does not presume global consonance, but rather produces it, with ultimate adequacy, as a simulation of universal authority. There is no eventual doubt – to Bitcoin – which came first. Absolute order is manifested in the chain. Were this not true, nothing ever could be.

§2.64 — “Once the CPU effort has been expended to make it satisfy the proof-of-work, the block cannot be changed without redoing the work. As later blocks are chained after it, the work to change the block would include redoing all the blocks after it.” System integrity is therefore identified with a robust past, and even with tensed time as such. What makes the past the past, that is, the separation of time, is indistinguishable from a resistance to revision. “As later blocks are chained after it, the work to change the block would include redoing all the blocks after it.” That which most incontestably demonstrates its resilience – by enduring into the future ¬– is the past. What has happened, alone, is realized. Time is here captured as it tenses,footnote:[In the Anglophone philosophical tradition, the most influential statement of the distinction between tensed and untensed (geometrical) time is that of John McTaggart, in his The Unreality of Time (1908), where they are labeled the ‘A-series’ and ‘B-series’ respectively. The missing element in McTaggart’s discussion, subsequently contributed by the diagonal conception of intensities, and then implemented by Bitcoin block-succession, is envelopment. From the perspective of classical transcendental philosophy ‘B-theory’ or tenseless time is simply not time. See Huw Price (1996), Time’s Arrow and Archimedes’ Point for an incomparably lucid defense of the ‘atemporal viewpoint’ in philosophy and physics.] in the execution of an ontological operation, through which Being is decided. In this way, the process dividing the future from the past provides a selective criterion. What has been discovered by the Bitcoin protocol, is that the model contract is necessarily timelike in this sense, to such an extent that it can implement time. Here’s the deal. That which is done has contractual integrity insofar as it is not easily undone. Irreversibility is the key.footnote:[When Benjamin Franklin concluded – prophetically – that “time is money” he surely could not have anticipated this equation bypassing all mediation by human effort, and locking directly into the foundations of the transaction as such.]

§2.641 — When the problem of time is apprehended as the principle architectural factor in the history of philosophy, it places modernity on exhibition as an epoch of teleological eclipse. The systematic suppression of explanatory finality within modernity anticipates, and envelops, the temporary retirement of time – or irreversibility – ‘in general’. As with all good things (philosophically speaking), the basic structure is profoundly paradoxical, or, more strictly, pseudo-paradoxical. The occidental intellectual modernity that rose in revolt against medieval scholasticism, under the banner of a mechanistic rejection of teleological thinking, was not only colored by intense religious commitments, it was also itself – still more twistedly – propelled by profound teleological inclinations. The comprehensive mechanization of causal concepts was the guiding telos. Scientifically-respectable causes were determined as implicitly reversible. Modernity, self-described in its name as the epoch of irreversible historical succession, was to be characterized by sovereign temporal reversibility, and thus by the abolition of time. This fertile mad loop (without precedent) might be compressed further, into the claim: Time had never been annihilated before. Extirpation of purposive explanation soon hardened into a commanding purpose, coincident with a distinctive cultural reproduction of nature. With consummate objective irony, a world determinedly stripped of anthropomorphisms accelerates into the Anthropocene.footnote:[Any programmatic elimination of ‘man’ as an explanans easily lurches into theoretical error – most especially when it becomes a mechanical reflex. In the case of the Anthropocene – a proposed geological epoch determined primarily by the deep geochemical impact of the human species – an empirical thesis is at stake, for which a principled antihumanist dogma has little to contribute. The legitimacy of ‘anthropic’ reasoning, which seeks to draw substantial consequences from ‘our’ existence as observers, merits comparable philosophical tolerance, which is to say: no less than partial immunity from accusations of anthropomorphic infection.]

§2.642 — The idea of telic compulsion (in general) was rejected by the moderns, in very substantial part because the specific social and historical order identified with it was undergoing a great refusal, involving tumultuous conflict of such proportions that the idea of common governing ends had become implausible, and in fact ideologically intolerable. ‘Mechanism’ was both an explanatory procedure and, relatedly, a commitment to the disintegration of social purposes, with special relevance to those new micro-social redoubts most indispensable to the formulation and testing of techno-scientific hypotheses, indispensable to germinal industrial capitalism. Modern mechanism thus arose as a counter-convergence, in which the multiple senses of freedom from interference found coherence. It was simultaneously an image of nature, captured in abstraction from divine intervention, and a distributed manifesto in defense of autonomous research practices. In proclaiming the irrelevance of ecclesiastical judgment to all matters of natural fact, modernity liberates mechanization, or initiates a mechano-liberalization, continuous with the impulse to algorithmic governance of our present time. The conspicuous – perhaps ‘apparent’ – paradox at work has provided the staple nourishment for philosophical reflection ever since. Over a span of five centuries, the seemingly contradictory cultural bearing that heads – simultaneously – into unconstrained volition and rigid mechanical determinacy has been bound together by the tacit aspiration to actualize a freedom machine. Bitcoin is, beyond all serious question, its most remarkable recent instantiation.

§2.643 — The transcendental is not the transcendent,footnote:[For non-philosophers, the temptation to confusion presented by the similarity of the words ‘transcendent’ and ‘transcendental’ is so seductive it amounts almost to a manifestation of terminological sadism. Unfortunately, this is a confusion that the critical enterprise is unable – even momentarily – to tolerate. Transcendental philosophy is the sole alternative to transcendent metaphysics. The terms are not merely distinct, then, but structurally antagonistic, or reciprocally defining. Abolition of the transcendent in the name of the transcendental is the whole of critique. ] but rather the rigorous dismissal of the transcendent (in the name of immanence). It is ‘that’ which cannot be transcended. Whatever cannot be surpassed, or even momentarily eluded, is transcendental. The term designates whatever is always already and everywhere in effect. It thus frames the contingency of things. In other words, it marks any announcement of arrival in absolute contingency as premature, in the same way that Kant walks Hume back from his expedition into philosophical hyperbole. The unnecessary is encapsulated within a system of indetermination, comparable to the physical limit of a global entropy maximum, against which local aberration is contextualized, by restriction. However contingent any particular occurrence may be, the transcendental structure of occurrence as such is invariant. This is only to say, critically, once again, that time itself cannot be apprehended as an intra-temporal phenomenon, or something in time. In granting this conversion, the intrinsic solidarity of time with a teleological problem has already been conceded.

§2.644 — Complexity, or emergent irreducibility, connects the thematics of telos (or leading end) with the transcendental. It invokes a synthetic principle of intelligibility that coincides with the whole, at the end, or at least on the way, and one that cannot be derived by an analysis – however exhaustive – of its parts, or its precursors. Equally, however, it is fully compatible with the most vigorous reductionism, allowing only that a number of parts does not disappear into its parts. A three-body problem requires three bodies, but also nothing extraneous to those three bodies, considered together as a system, a number, a multiplicity, or as such (in their numeracy). It is a thing, consisting of its parts taken together, and nothing else. The error at work in any attempt to push analytical reduction beyond this point is precisely metaphysical, in the critical sense. The systematicity of the system is not an accessible datum within the system. It has an irreducible mathematical integrity of its own, and in this way alone are there ‘things’ (or real objects) at all.footnote:[Natural science has been perpetually tempted by the thought of a world without things. This results inevitably from its Oedipal animus against the Aristotelianism that was relayed through Scholasticism, and which – even many centuries later – persists as a vivid infant trauma. (“Show us on the doll where the Schoolmen touched you.”) As systems – rather than generic regularities – increasingly become its principal objects of methodical fascination, however, the restoration of emergent individuals (or real things) becomes ever more inescapable. If a refusal of ‘teleology’ in the name of a radically naturalized ‘teleonomy’ is considered essential to the preservation of modernity’s cultural hygiene, it would perhaps be pedantic to object. Pre-critical teleology – which pretends to grasp the telos as an object – is indeed a fundamental philosophical error. From the critical perspective, there is no real telos beyond the emergent systematicity of the system considered. ‘Goal’ and spontaneous order are the same. It can thus be noted immediately that metaphysical teleology falls prey to a psychological projection. Rather than an outcome, the end is interpreted as an intention. The neuro-philosophical dissolution of the intentional phenomenon is therefore structurally complicit with the critical rigorization of the teleological idea.
If there were no real emergent individuals, the sole science with a definite domain would be physics – or more precisely cosmological physics – whose object is given by the universe. It follows, therefore, that many existing scientific disciplinary boundaries have been poorly drawn, and subsequently defended, proudly, on the grounds of an erratic empiricism – still associated in fading memory with the overthrow of an arcane medievalism. Of course, it would require bizarre naivety to imagine the natural sciences educable on this point. They, too, have their historical destiny – which is essential, or integral on this question. If they were not – through systematic artificial instinct – repulsed by every prospect of concession to teleological thought, they would be something entirely other to what they are. They would have had a different birth (and with birth, comes path-dependency). Yet, without a critically-reduced teleological discipline, scientific objects remain arbitrary. Biology, for instance, is the mock-up for a still-virtual science, whose various components are rigorously derivable from the systematic decomposition of a comprehensive ‘terrestrial biosphere studies’. Outside this framework, ‘What is life?’ if not necessarily a disastrously misconceived question, is at the very least vulnerable to gratuitous confusion, insofar as it erases singularity from its object. It is only when the still-infant questions of ‘xenobiology’ are raised that the contours of accessible biological factuality sharpen. Life, as we know it, falls out of a singular sequence of events, or singular thing. In all of its complexity – historical and ecological – it elaborates upon an occurrence. Generic biological reality is simply unknown. Only the haziest inferences reach out towards it. It is increasingly recognized, at least enough to be link:http://cosmos.nautil.us/short/73/why-most-planets-will-either-be-lush-or-dead[troubling], that “… life is not a minor afterthought on an already functioning Earth, but an integral part of the planet’s evolution and behavior. Over the last few decades, the Gaians have pretty much won the battle. The opposition never actually surrendered or admitted defeat, but mainstream earth science has dropped its disciplinary shields and joined forces with chemistry, climatology, theoretical biology, and several other ‘‐ologies’ and renamed itself ‘earth system science.’”
Teleological framing is the corrective to an always-premature universalization. In this way (alone) it is critical. Ironically, it is the contrary mode of illegitimate universalism that is, in any consistent application of the word – when applied in its denigrative sense – medieval. To leap from local regularities to a cosmic norm is to hasten to the unframed signals of a transcendent revelation. Even physics is vulnerable to this temptation, when it seeks to construct itself in unearned abstraction from cosmology. Among the emergent correctives in this case is the dissolution of ‘the universal’ in the multiverse, which fixes the basic conception that the universe, too, is a thing. According to the teleological corrective, all constants descend from singularity.
Allergy to the word ‘teleology’ is positively remarkable, because it so perfectly exemplifies the phenomenon of terminological flight. It demonstrates, in all innocence, the influence of critique within the linguistic realm, which is otherwise – and cynically – displayed by the motor of interminable (‘deconstructionist’) auto-revision. Running, in this way, rarely engages the basic problem that drives it, and thus tends to become perpetual yet without actual distanciation – like the flight of a hunted subject through a nightmare.]

§2.65 — Teleological understanding is no less vulnerable to metaphysical error than any other systematic cognitive process, but it is also no less tractable to critical correction. What is required, naturally, is the rigorous elimination of the supernatural element. If there is no distinction, in the end, between an object and a telic object, it is because being an object is hard. It is only when almost everything is missed, that objects can be casually accepted as ‘givens’footnote:[“Nothing is given, everything is taken,” Nietzsche writes.]. This is the critical insight, which reliably aligns transcendental apprehension with a certain ‘subjectivism’. Kantian ‘Copernican Revolution’ in philosophy construes objectivity as a product. It is the output, rather than the raw material, of a synthetic process. Critique apprehends objectivity as a problem, and a precarious attainment. That is why critical influence is marked by a systematic subjectivism, often implicit, but also not uncommonly emphatic – and typically bound to a local ‘Copernican Revolution’ in the field considered. The ‘subjective’, in all these various cases, does not designate a positive redoubt, but rather a mere default, established negatively, in anticipation of an objectification process. The object has to be made, and is not therefore previously available, as a foundation. Among Austrian Schools economists, objective price arises solely from the catallactic interplay of subjective preferences, while among Bayesian probabilists, objectivity in estimation is achievable only through the rational updating of subjective ‘priors’, to mention only two critical examples. The subjective stance in such cases is not a dogmatic commitment, but rather the opposite. It is a skeptical suspension, corresponding to the status of objectivity as a production. Subjectivity is work not yet done. That which has not been earned, in respect to an attribution of reality, falls automatically onto the side of subjectivity. Contra the later, inflationary, German idealists, what is seen here is not the expansion of a claim, but rather the delimitation of an entitlement.

§2.651 — The teleological object is an emergent individual with inherent principle of intelligibility (providing the basis for functional explanation). Essential to this mode of apprehension, already with Aristotle, is the understanding that there is no difference between the specific teleological idea (telos) and the rigorous foundation of a distinct science. Ever since it was discarded by the modernists as an archaism – for reasons very briefly sketched above – the indispensable notion of real individuation has sought stubbornly to recompose itself, most clearly in those cases where an infant scientific enterprise has struggled to determine its domain. In respect to the natural sciences, philosophy has inherited an inescapable responsibility, which is not easily differentiated from a ludicrous pretension. In understanding itself, as a transcendental discipline, it cannot but say that even if the sciences were to be correct on every question of fact, without exception – and this is a wise assumption for philosophy to make, despite its patent extravagance (since it encodes a teleological truth footnote:[Insofar as the natural sciences are wrong about anything, _they tend not to be._]) – they would nevertheless not know at all what they are talking about. Their modernity makes it impossible for them to know, and in regards to their historical function it does not remotely matter that they do not know. They are rarely required to be realistic about things, or in fact even to glimpse what this would mean.

§2.652 — In reality, between the transcendental and the teleological, there is finally no difference. Both are final. No principle of constancy or consistency exceeds that provided by what is coming (what has always been coming), which is time. Only that which cannot be reversed remains the same. System, or irreducible individuation, provides the bridge. Consider the telic objects of principal concern to us here, in nested order – Capitalism (or Modernity), the Internet, and Bitcoin. Each incarnates an ultimate rule that is in reality indistinguishable from a singular existence. Capital is the growth of abstract value. The Internet is distributed communication. Bitcoin is absolute succession. The apparent extreme generality of each definition dissolves upon examination, into an artifact of low-resolution. “How is X actually implemented?” With this decompression of the existential copula, the teleological content of the definition is extracted. The target of the process provides its principle of intelligibility. We can ask, each time, with only minimal hesitation: What is it trying to do? Each real individual, without exception, strives to become what it is, or it ceases to be. What is happening? What is this piece for? How does it work? – These questions are all inter-translatable. There can be no real system under interrogation without them.

§2.653 — The importance of the teleological principle to this discussion is most evident in the case of limit concepts (which Kant calls ‘regulative ideas’). Among the most prominent of these, and the one bound with greatest intimacy to the sciences of man, is homo economicus. This is a concept that the tradition of political economy has been conspicuously incompetent at defending. If it is considered to be a mere abstraction from empirical sociology or anthropology – as a kind of distilled datum – it will prove, indeed, to be indefensible. No such entity, beyond a very pitiful level of approximation, awaits discovery in the world. Were economic man only a poorly-described fact, then ‘behavioral economics’ would be entitled to the triumphalism it is already illegitimately enjoying. Homo economicus is not, however, a datum, but rather the target, or extrapolated optimal outcome, of certain definite historical processes, i.e. a telos. It is differentially actualized, in the private accomplishment of relative economic rationality, or advantage, and – more importantly – selected for at multiple levels, under conditions of capitalistic social organization. It thus models game theoretic competence, with the implicit heuristic: when describing how a game works, assume players who are able to play the game. The game will find, sift up, and train, such players if permitted to run. That is the basis of the true culture war inherent to capital formation. Implicit within capital is a template for the kind of people it wants, and which – given only time and opportunity – it will automatically produce. If humans lack the plasticity to compete in these terms, or revolt against the roles and templates automatically laid-out for them, then artificial agencies – ‘DAOs’ – will be fabricated to play the game instead. Questions directed to the accuracy of representations thus tend to distract, in this regard. A regulative ideal only describes actuality as a sub-function on a roadmap.footnote:[There is finally far more insight in the leftist objection – “We don’t want to go this way” – than in the theoretical ‘correction’ to the regulative ideals of classical political economy proposed by behavioral economics. Homo economicus is a criterion for the determination of socio-economic irrationality. To imagine, then, that the exposure of systematic patterns of economic irrationality could conceivably amount to a telling theoretical criticism is a symptom of profound confusion. Since anthropos has no teleological status within classical political economy, anthropology – i.e. behavioral economics – is unable to criticize anything on the level that matters. The crucial teleological point is this: If economic rationality could be derived from mere anthropological description, it would have no function as a motor of competitive advantage.] Perfect competition is a regulative idea of comparable relevance, and philosophical status. If capital production were not inherently telic, its sub-components might be found merely scattered among the world of objects, as empirical curiosities. But it is (so they are not).

§2.7 — Immanence is a selective principle (a criterion). Only consistency survives. Resolution of the double-spending problem means exactly this. When conceived lucidly, Bitcoin is simply critique. In other words, a formally-specified machine for dispelling metaphysics exists – and is running – now, under conditions promoting its intensive accumulation. In this regard, Bitcoin is the inheritor of Nietzschean ‘European Nihilism’ – or materialized critique in its unfolded, historical expression.

§2.71 — Negatively apprehended, nihilism corresponds to a ‘loss’ of transcendence. Some proposed – or (more commonly) merely accepted – higher order, culturally sustained by nothing of any greater security than a dogmatic metaphysics, slides into the abyss. It cannot be effectively defended. This is the most readily popularized narrative, adapted specifically to the dilapidation of Christian monotheism – the notorious ‘Death of God’. According to this construction, nihilism is a specifically world-historic mode of mourning. It corresponds to a disappearance of meaning, through loss of a referent previously revered as an indispensable exterior support (a vulgar God, or god-like powers, as attributed to the agencies of a state, or any other ‘trusted third party’ of sufficient dignity, such as a central bank). In this sense, nihilism abbreviates the collapse of transcendence, or the work of critique. Negativity is redoubled, first in the disjunction that determines ‘the beyond’ (transcendence), and then in its subtraction. Hence the cultural dull grief of a self-cancelation that can appear as less than nothing, such as that manifested in the stereotypical passage from theism to tedium. Yet the ‘meaning’ of nihilism is not exhausted by its depressive connotation. In its positive sense, nihilism closes a circuit. Rather than a registry of loss, it is a principle of sufficiency – even of ‘liberation’.footnote:[Doublings, twinnings, and ambivalences are everywhere here. Christianity is at once that which falls into decrepitude, catalyzing the process of European nihilism, and the anticipatory dramatization of the death of God. Messianic religion is accomplished through its sacrifice. The response, within the Nietzschean text, couples morbid diagnosis of decadence to themes of exorbitant sufficiency. Decline (Untergang) glitches into an ‘overcoming’ – which is equally a shedding – through a selection mechanism summarized as eternal recurrence. “What is falling, that one should also push,” spake Zarathustra. Experiment in what one can do without. This is the undercurrent of austerity. In the libertarian traditions that preserve the basic orientation of classical liberalism, such a conversion of the negative is insistent. Negative rights, negative freedoms, and independence with emphasis upon the negative prefix are the whole of an economized positive program. Strip-out all superfluous axioms. Do without them. Between the elimination of metaphysics, and the positive modern philosophical program, there is no difference.] Certainly, and strictly, it is a production of independence, or autonomization, marked by a completion – or closure – that appears premature when referred to a bypassed element no longer presumed indispensable. The residual negativity of nihilism is then confined to the elimination of a dependency. It characterizes a relatively compact process that does not call upon anything beyond itself. Once again, the monetary example is to be preferred over the linguistic one. There is no backing. The remarked ‘loss’ of a trusted support is not distinguishable in reality from the discovery of an economical potency. The machine works without it.

§2.72 — Algorithmic governance subtracts discretion. It economizes government, in at least two senses. Government extravagance is formalized at the highest level of philosophical principle, and systematically eliminated through application of an economic criterion. The political element is determined practically – which is to say surgically – as superfluous cost. Antagonism, relative to an extant structure of authority, is intrinsic to the process, and essential to its positive nihilism. The point of critique is to kill stuff.

§2.73 — Bitcoin instantiates spontaneous (or apolitical) consensus, without authoritative central representation, escalating the intrinsic trend of the Internet. It manifests an aboriginal coordination between the elements of a multiplicity under conditions of simultaneity (or zero-communication). This is, of course, nothing more than an exceptional approximation to the ideal of a distributed system. But distributed systems do not spring into actuality from out of their ideal form. They have to be built. They have to and will be built, once their conditional ignition threshold is crossed. At the historical – i.e. ‘anthropomorphic’ – level, this inevitability is nothing other than Modernity, apprehended through its teleological structure, or defining gradient. That is why there is perhaps no pattern that more reliably characterizes the culture of Modernity than the rhythmic re-ignition of spontaneous order as a theoretical (and ideological) topic. The history of nihilism can be told entirely in such terms. There is always implicit reference to a subtracted overseer, whose removal defines the intensification of the process. “The death of God” provides the cultural allegory. Practical abolition of the State is set – from the beginning – as the horizon. A machine without metaphysics is anticipated by critique – but that takes time.

§2.8 — Productive perpetuation of the critical tradition sets, as a preliminary task, discrimination between the necessities of transcendental philosophy and its contingencies.footnote:[This task is ‘preliminary’ because it is crudely (or pre-critically) formulated. Rigorization of critique coincides with the swapping-out of categorical understanding for diagonal conceptuality. ‘Necessity’ and ‘contingency’ – which apply solely to comprehensible objects – are patently ill-suited to the conditions of possibility for objectivity as such. An adequate formula could only be problematic, pseudo-paradoxical, and cryptic. It is expressed as a contingent necessity, or necessary contingency, compressed into a critical conception of chance. The philosophical work of singularity – as transcendental event – has obvious and extreme relevance. The religious evocations of an absolute occurrence do nothing in themselves to dispel its cognitive compulsion. Critique has to be some such thing, if it is in reality anything at all. As a matter of indissoluble principle, no mere datum of intellectual history can provide philosophical direction. Comparably, critique gropes towards self-apprehension as an essential accident (with accidental essence).] Prominent among these latter is the temptation to philosophical anthropology, characterized most significantly by the identification of the human subject as the primary locus of time-synthesis. In this regard, the Bitcoinization of transcendental philosophy is direct, and drastic.

§2.81 — The time of the blockchain is absolute, non-geometric, synthetic, and intensive.footnote:[To briefly recapitulate these characteristics, in order, the time of Bitcoin is:
(a) Absolute, by definition, since time-relativity is essentially identical to a double-spending predicament.
(b) Non-geometric, since succession cannot be adequately modeled in space, unless, tautologically, by designating a ‘time-line’ or ‘time-axis’ whose temporal intelligibility is strictly derivative. On any line, time-gradient can be referenced, but not described.
(c) Synthetic (rather than analytical), because innovation is intractable to anticipation, having the cryptographic structure of a trap-door function. Discovery process is irreducible.
(d) Intensive, because the order of succession is serial envelopment.] It produces a univocal order (sequence), and in the end does only this. Sequential ambivalence would make the double-spending problem intractable. Bitcoin teaches that a DSP solution cannot be less than absolute time. Bitcoin’s engine of selection is priority, primacy, or ordinal privilege – being first in line, or first past the post. Bitcoin mining is a race. Insofar as the winner of the race can be decided automatically – without controversy or irreducible relativistic complication – then sequential decidability is established in general. Philosophical modernization and the production of secure money are, at this precise point, indistinguishable, not only logically, but also ontologically, or numerically, through the singularity of their occurrence.

§2.82 — The most modest plausible interpretation of Bitcoin is that its tacit perspective replaces (a lost) absolute time. A stronger proposal is that absolute time is, with the blockchain, inaugurated. To articulate the thesis (more informatively) in reverse: The philosophy of absolute time anticipates the blockchain. In still other words, it retro-chronically depends upon it. Only in the blockchain does geometrically-irreducible arithmetic series find instantiation. Primordial time synthesis is henceforth something the technosphere knows how to do.

§2.83 — By the strictest conceivable (i.e. transcendental) principle, nothing beyond the blockchain has authority in relation to the blockchain, or could have. Were this not the case, a ‘trusted third party’, or organ of transcendent oversight, would remain operative, such that – reciprocally – the minimum conditions for the realization of Bitcoin would remain inaccessible. In other words, the Bitcoin protocol is transcendental because it is essentially beyond appeal. The idea of a superior tribunal is immanently nullified by it. Furthermore, not only is the Bitcoin blockchain transcendental, and thus unsurpassable, but also the model of the transcendental installed by the blockchain is itself unsurpassable. ‘The buck stops here’ in an ultimate definition. A certain ‘end of philosophy’ is thus reached. To argue otherwise is once again to propose an actual, or merely possible, court of appeal where there cannot, in principle, be one. There is nowhere to take a case against the blockchain and its statement of reality unless to a manifestly – i.e. effectively – inferior authority. All stubborn metaphysical commitments to the contrary case lack a realizable criterion, and can only regress to politics as a proxy. They might – and in fact will – be entertained, but no one will seriously bet upon them. Their enforcement requires escalating coercion, destined to reach levels that can only eventually prove impractical. 