[preface]
= 0: Foreword

§0.00 — Crypto-current exists if secrecy has a trend. Such a suggestion is naturally obscure. It coaxes attention toward the surreptitious direction of things. ‘Crypto’ is simultaneously the topic, and the retraction of the topic. This evasiveness is compounded by the complexity of its complement. The current eludes docile conformity with the order of objects. This is – apparently – quite independent of any strategic commitment to concealment. It is a flow of time, electricity, footnote:[Crypto-Current is not, by intention, a book about electricity, but it is quite probably a book about electricity nevertheless. Crypto-current (the thing) works itself out that way, in stubborn obscurity. Electronic publishing is no more than a late phase of its eventuality – although, essentially, among the most conspicuous. Electric current – measured in Ampères or ‘amps’ – conventionally takes the algebraic symbol ‘I’, derived from the French intensité de courant (current intensity), as used by Ampère in the formulation of his force law (1820). It is exactly current intensity, apprehended at a superior level of abstraction – and therefore without the benefit of any yet-stabilized, compact notation – that provides our topic. When posed in the Kantian fashion, our question – determined now at a scale that is bound to escape us – asks: How can there be anything like current, in general? It is, of course, time that is put into question here, but in such a way that electricity – and more specifically hyper-electrification – conducts the interrogation. Even within this widened domain, Ohm’s Law (1827), I = V / R – current is equal to potential difference over resistance – provides a definition we will not, and actually cannot, find reason to depart from, unless in an abstract direction. Our task, rather, is to generalize it, without subsidence into metaphor. Current is not a figure for something else. It is the thing itself – or real time – even, or perhaps especially, when it is most artificial.] and cash – a turbulent conceptual confluence. Current events are the only kind. If we are unable to step into the same current twice, it is because of what irreversibility has secured in the past. A double blockage then – produced, in a stream, as _concealment_ and as _sedimentation_. Subsequently, everything we have to say here is already over (but unseen).

§0.01 — _Is it really necessary to be so cryptic?_ This question will do, as a trigger. It seems – however querulously – to ask everything our title seeks to, and more than a book is able to comprehensively engage. The implicit reciprocal: Is it not possible to be clear? What begins with a minor irruption of cognitive irritation, agitated by a few specific words, opens into a history of secrecy invested with hazily-discernible momentum, and beyond, into the dark Herakleitean gnosis – matrix and crypt of Occidental philosophy – Φύσις κρύπτεσθαι φιλεῖ (“Nature loves to hide”).footnote:[The surviving Fragment 123 of Heraclitus (Φύσις κρύπτεσθαι φιλεῖ) hides much within its natural English translation, _Nature loves to hide_. A glance at the Greek is required because it is especially important for us to note that concealment is already crypto. In its invocation of a crypsis intrinsic to nature – an _integral obscurity_ – the fragment captures a topic anterior to any dissociation of epistemology from ontology. It evokes an active or strategically self-directed dynamism of the unknown. Concealment is determined as a potency on the side of the ‘object’, or rather – far more precisely – the side of ‘that’ which eludes determination as objectivity, rather than merely a deficiency attributable to the subject. ‘How do we know?’ is far too confident a question. ‘How does it escape knowledge?’ interrupts the epistemological presumption. ‘Ignorance’ is thus construed positively, as a natural production.] The provocation of integral obscurity leads to the 10,000 things.

§0.011 — Glimpsed at its distant pole of unbounded abstraction, the cryptic is the ultimate philosophical enticement. At this point of origination, two-and-a-half millennia behind us, philosophy was nothing other than abstract cryptography. Its concern was hiding. If cryptography is currently subsuming philosophy back into itself, the historical figure thus sketched is a great cycle – an obscure return. Restoration – closing an epoch (of financial discretion, most superficially) – is also an irreversible liquidation, into currency. Registered within the terms of the transcendental or critical philosophy, it is a departure from the pseudo-object of ‘the present’ in the direction of current time.

§0.0111 — Streams run downwards.footnote:[In Chinese language and conception, drawn from the practicalities of water clocks, 下 (xià) or _down_ is the _direction of the future_, while 上 (shàng) or up is that of the past. Temporalization is descent. Water models time, to some degree of adequacy, while also hiding it. As already for the Greeks, and still for us, it _in some way flows_. If translated into the terms of occidental theology, The Fall never ended. Onwards is down, at least in abstract inclination.] Engagement with Bitcoin brings us into communication with hidden inclinations, whose indicators mark productions of directionality – gradients, or temporalizations.footnote:[Morgen E. Peck writes: “… a bitcoin miner can … be confident that the other miners are not changing entries on the blockchain, because in Bitcoin there is no going backward.” A re-installation of irreversibility is the primary achievement.
http://spectrum.ieee.org/computing/networks/the-future-of-the-web-looks-a-lot-like-bitcoin] Between real succession and such abstract inclines there is no difference. Entropy describes such an ‘arrow’ most basically, but upon this are built a succession of stream-tapping technologies (hydraulic, thermodynamic, informatic), reinforced by directional mechanisms, beginning with clockwork ratchets, and then proceeding – from the early industrial-era – through check-valves, into electronic forward-bias diodes (rectifiers), and software-implementations of one-way or ‘trap-door’ functions that support asymmetric crypto-processes, and irrevocable contractual commitments. Current emerges from the machinery of time, which is to say from _operational asymmetries_. ‘Flows’ are easily – and often lazily – invoked, without even notional attention to their engineering details. Far too much is already understood about the mechanics of irreversibility to leave such vague suggestions as a stopping point.

§0.02 — Economies are assembled from flows. Unsurprisingly, therefore, their native codes are currencies, or current-signs. As societies mobilize matter-energy resource streams, their monetary conventions register these flows by inversion, and strict reciprocity. Hole-flow in electronics is a close analog. Every non-barter commodity exchange, or non-financial transaction, catalyzes a flow, by pricing it. The ‘real economy’ is thus automatically captured, by a monetary code, even when – as is overwhelmingly typical – this quantification through signs is never aggregated. Since money systems install an intrinsic economic intelligence (preceding all reflective theorization), economics – uniquely among the sciences – inherits a field of objectivity whose arithmetization has already taken place. This same delicate shadow, cast into business ledgers (pre-denominated by currencies), at once facilitates and registers a system of flows, in a twin production of economic objects. Business is recorded in the way it is produced. Dynamization of the commodity – or economic circulation – is not reducible to, but nevertheless strictly corresponds to, transference of signs.

§0.021 — The economic event, then, is co-original with its semiotic double. It is enabled by signs, before being represented by them. Even the secondary processing, through aggregation, of such information has a pre-theoretical foundation. Powerful economic agencies – most significantly the state’s tax authorities – concentrate commercial data, long before scientific political economy begins to re-compile it, as an analytical object. Logos arrives late.

§0.03 — It approaches a truism – although not one for this reason to be glibly dismissed – that philosophy assumes, as if by right, a position of sovereign authority relative to everything it touches upon.footnote:[Among the nagging contexts of this book is the emergence over recent years of a neo-humanist philosophical school, constituting the dominant development of speculative realism. While specifically differentiated from earlier modes of humanist thinking by its consistent collectivism, it remains deeply conservative in its metaphysical commitment to the irreducibility of reflective human cognition to non-linear machine-process. In this regard, it affirms a species of philosophical writing understood as transcending the algorithm in general, as if – even after Gödel – we could presume to set such limits with confidence. It is a school that resonates with a specific neo-Kantian lineage, inflected terminologically through the work of Wilfrid Sellars, and the resuscitation of a ‘space of reasons’ irreducible to anything cognizable within the space of a supposedly strictly-bounded ‘understanding’ that is now carried techno-historically by comparatively informal engineering initiatives and disciplines. That which can be justified, it is asserted, cannot be dissolved into mechanical production, in principle. This claim is both bold, and traditional. By its very nature, it defies all prospect of determinable testing. Since any possible digital sequence is potentially the output of a program (and actually of an infinite number of programs), there cannot be any definite criterion of cognitive competence, when this is formulated in terms of a transcendent rationality. Testable performance is inescapably vulnerable to the prospect of mechanical emulation. Definite criteriology has, therefore, to be surreptitiously side-lined if the algorithm, in general, is to be subjected to philosophical delimitation. Whatever it might possibly be that no ‘algorithm’ could do, in principle, cannot – in principle – be clear. Critique is demarcation. It sets the limits of a topic (of pure reason, practical reason, and judgment, inaugurally). Crucially, these critical exercises are immanent, i.e. limited to realizable tribunals, or fields of judgment. They mark horizons. No Archimedean position is available to them. They do not ever in reality successfully project beyond themselves, to set the limits of something outside, in an attempt to ensure security against it. In other words, according to a proposal drawn directly from the philosophical tradition, critique has no rigorously conceivable speculative employment. Yet it is exactly some such speculative inflation that is required in order to assert the irreducibility of thinking to complex machine behavior. If this is the only way for philosophy to reproduce its effective cultural dignity, it can be confidently predicted that it will not long survive the techonomic intelligence explosion in which it is factually embedded. Transcendence over against the machine (in general) is the epitome of metaphysical presupposition. Neohumanism, then, is a consistent implicit theme here, as it will be far beyond the bounds of this discussion. It is engaged here, primarily, via a route-around – or an unbound evasion. The bypass operation is the critical current. What cannot be stopped also should not be.] A discussion of Bitcoin and Philosophy amounting only to a confirmation of this stance would merit contempt, even if it were packaged as humor. Since any attempt to philosophize about Bitcoin would already be a joke, it is better to get it. Bitcoin seizes philosophical attention because it is already doing philosophy – or what philosophy is still (on ever rarer occasions) expected to do – and at multiple levels. It tells the truth. Bitcoin is not only a recognizable philosophical statement, but also, and more importantly, a philosophical automatism, a synthetic philosophical machine.footnote:[The techonomic horizon, for ‘us’, coincides with the impending crisis of historically-actualized artificial intelligence. Encapsulated within this by now manifest potential is the comprehensive automation of philosophy. It cannot be simply assumed, therefore, that professional philosophers will respond to the prospect with detached equanimity. The simulation – and thus replacement – of their defining activity is integral to the hypothetical outcome under consideration. Under such circumstances, a coherent defensive reaction is the natural expectation. This is, of course, what we see. We will see much more of it. Yet there can be no stable hierarchy, preserving the superiority of philosophy over against a Critical Automation Theory (of the type advanced, for instance, by Luciana Parisi), or some less explicitly formalized analog. Automation is no more tractable to philosophical reflection, in principle, than philosophy is practically tractable to automation. The dominating considerations in both cases are synthetic, or experimental. A circuitous skepticism balances the technicization of understanding against the understanding of technicity, with both locked into a productive cycle. Learning fuses cybernetically with the machine. There is no Gordian Knot here for traditional authority to sever. Instead, there is a ‘question’ that cannot be confidently distinguished from an informal technical research program, and which therefore shrugs off non-ambivalent philosophical determination. An armchair philosophical objection carries no serious weight compared to something coming together in the garage.] It not only philosophizes in the manner of a man – although this is its certain prospect – but also finally in the way of an angel, or a lesser god. The ‘intellectual intuition’ (Intellektuelle Anschauung) that is for Kant a mortal impossibility, is for Bitcoin an operational principle. It is destined to close upon itself, and thus know itself. By becoming time, Bitcoin promises an exhibition of unleashed thought, in a way no introspective anthropology ever can.footnote:[These will almost certainly seem to be inflated claims, even when attributed to sheer efficient multiplicity. That is why our credence is being effectively bypassed. Modernity has disconnected our doubts from any system of permissions. What cannot be believed is no longer preventable.]

§0.031 — Throughout this book, ‘philosophy’ is employed freely as an abbreviation for ‘modern philosophy’, which is in turn consistently conceived – tacitly when not overtly – as critique in its (roughly) Kantian sense. To philosophize on any subject over recent centuries, as still today, has been to criticize, in the positive acceptation of this term, by differentiating the transcendental format from the empirical datum, and then resolving – or, stated more realistically, negotiating – the boundary conflicts between the two.footnote:[Transcendental-empirical difference is very far from being an uncontroversial conceptual commitment. Within the Anglophone world, its most celebrated critic has been Willard Van Orman Quine, whose ‘Two Dogmas of Empiricism’ (1951) assaults the conceptual foundations of analyticity. Logical identity cannot find secure grounds in definition, Quine argues. The lexicographic features of any term are never simply given, but must always be produced. Language has no meta-level logical characteristics, capable of securing analytical judgments. Along these lines, an attempted re-absorption of the critical impulse into an expended empiricism has been the dominant Anglophone response to the transcendental blueprint for the modernization of philosophy. Such an approach coordinates well with the techno-empiricism of the computer age, in which programs are processed as data. Between codes and information, protocols and applications, there can be no logically secure hierarchy, once Turing-complete digital computation is at work. Yet, from the partial perspective of the crypto-current, it is obligatory nevertheless to dissent. The resilient value of the analytic-synthetic distinction lies in its emphatic asymmetry. That is ‘analytic’ which can be conveniently checked, while the ‘synthetic’ has to be laboriously discovered. Cryptography essentially coincides with this distinction. We are thus, in passing, compelled to dismiss Kant’s identification of synthesis with simple addition (“7 + 5 = 12”) as misconceived, and misleading. It makes no sense to discuss the analytic, or synthetic, except in regard to reciprocal asymmetric operations, exemplified by trap-door functions. In the most significant instance, the analytic-synthetic divide runs between arithmetical production and factorization. The rigorous content of the distinction is work, in the sense given to this term by computer science. Its entire domain is exhausted by twin procedures of asymmetric facility. In its scientific application, it divides theoretical construction from experimental replication (or, once again, discovery from checking). Nature only has definite secrets in respect to this split method. If ‘thinking’ – or experimental discovery – were as economical as testing, or attempted result replication, there could be nothing like science at all.
] However it is specifically articulated, critique isolates a properly transcendental productive principle, or function, which is constitutive of a domain rather than existing as an item within one. It thereby marks a unilateral or ontological difference (which is to say, a discrepancy irreducible to any relation between terms that are internal to the domain considered). Critique is, necessarily, the theoretical assertion of a non-empirical partition. Through critical abstraction, the consistent order of the system considered is liberated from its specific instantiation, to become a philosophical preoccupation, immunized against the distractions of any merely factual controversy about its content, but also – simultaneously (or diagonally) – from purely formal considerations of its internal logical organization. It is committed to a zone of positive discovery (which logic cannot be) that is systematically enveloping (as no empirical concern can be). Philosophy, as such, no longer has anything else whatsoever to attend to. If philosophy cannot be critique, it cannot be anything (that matters within Modernity). That is its essential immanent Law.

§0.032 — The target of critique is ‘metaphysics’ – conceived as a specifiable cognitive error. As determined by Kant, at the origin of the transcendental-critical enterprise, metaphysics is understood as the systematic attempt to apprehend (‘transcendental’ or ultimate) conditions of objectivity as if they were themselves objects. The repudiation of this effort can be summarized with approximate adequacy in a phrase that serves as a critical war cry: objectivity is not itself an object. This is to borrow freely from the critical framing of metaphysical error as it is found, compactly formulated, in the Heideggerian ‘fundamental ontological’ re-statement of transcendental philosophy. Being is not a being.footnote:[For the purposes of its employment here, ‘ontological difference’ (between Being and beings) is considered to be no more than a restatement of transcendental-empirical difference, of negligible philosophical originality. It is not adopted as a marker of penetrating inquiry, therefore – still less of Heidegger scholarship – but solely as a resource valued for its pedagogical practicality. The term is validated for this purpose precisely insofar as the structural integrity of critique is economically conserved by it. Being is not a being. In this formula, the basic transcendental insight is captured with what is probably unsurpassable economy.] More significantly, for our current purposes, it can be conveniently extended to apply to contemporary techno-social arrangements and communications apparatuses by way of a comparatively simple translation protocol. ‘Metaphysics’ – over against which disciplined philosophical critique emerges antagonistically – is instantiated by any identification of a systemic function with some node internal to the system considered. It can therefore be readily seen that the ‘flattening’ of a network, through the elimination of system-critical, concentrated, indispensable nodes, which is to say through the distribution of its efficient principle, is an exact – if abstract – execution of a critical operation in the Kantian sense. A network is a critique.footnote:[Critique is anti-Archimedean philosophy, and in this strict sense an intrinsic anti-rationalism. It is directed against the pretensions to super-ordinate theoretical leverage which define metaphysics. Every claim to exception from immanence falls prey to it. Its sole empirically exorbitant proposition is that the whole permits no oversight. No ‘view from above’ can be true. Critique thus supplies the schema for that flat epistemology which empiricism requires and fails, itself, to produce. Its historical mission is to make the world safe for empiricism (i.e. techno-science). It can therefore be understood as modernity’s watchdog. Liberal civilization knows no higher principle of security. Its enemies are ‘churches’ with global ambitions, which is to say universalizing abstract-ecclesiastical authorities. When all relevant terms are stripped of encrustation with maximum rigor, critique is accurately characterized as anarchism in philosophy. It is that, alone, which cannot know any higher law. Whatever tries to transcend it can only repeat it, or less. We call this time, which can never be anticipated or out-lasted. Above Temporalization there is nothing. To engage in critique is to think in the name of time.]

§0.04 — Already, at the most naïve level of its acceptation, ‘Bitcoin’ is a word that refers to at least three things. Of these, the most elementary – although today least invoked as a definition of the term – is a succinct, technical paper, in whose catalytic code everything was, in a certain sense, already implicit. There is nothing obvious about this terminological development. To speak of the ‘critique of pure reason’ is first of all to name a book, even though (no less than with Bitcoin) it is the book’s ‘object’ that is being named. Critique of pure reason (the ‘thing’) is in this case a delayed signification, despite the fact the title says nothing else. In the case of Bitcoin, this system of acceptations is conspicuously inverted. ‘Bitcoin’ is not understood primarily as a paper,footnote:[The word ‘paper’ slides easily into the digression queue. After all, it might be convincingly argued that reference to the ‘Bitcoin paper’ has already surrendered to a linguistic legacy of peculiar inappropriateness, and thus to laughable anachronism. ‘Paperlessness’ is a retrofutural and thus historically ironized idealization of the electronic landscape. It is either pseudo-teleology or – far more probably – premature forecast, tacitly engaged by this and any other discussion of digital information, even prior to a collision with the thematic juggernaut of ‘paper’ money. If ‘papers’ are still with us – even when they have only ever been incidentally propagated in a ‘dead tree’ medium – it is because history is a loose sheaf, rather than a neat stack. Since technological epochs co-exist, simultaneously, anachronism finds its avenues in space, even more than in time.] perhaps because it is not primarily an argument. Its nexus of persuasion has migrated outward, in close association with the meaning of code. Critique undergoes accelerating automation.

§0.041 — The philosophically pressing motive for hesitation – however momentary – at this point of origin, where the balance between the virtual and the actual is most dramatically precarious, is to hold open the question of primordial introduction, even as it tends to eclipse itself. Already, during this remarkably brief embryonic phase, when Bitcoin was implemented only in words, it was at least double – at once a title and a topic. From the beginning, the term pointed beyond the name of a text, towards a virtual entity, something that could be made to happen, or that was, in being rigorously outlined, already being made to happen. In being drafted, it was in fact initiated – even released – and through its ‘preliminary’ scripting it had already been informally pre-programmed, or practically introduced. Bitcoin has existed from the moment it was named (and its origin could be pushed still further back). Such occult potentiation of the semiotic event is what it is to code, in the modern sense of this term. It is something much more than description. As code, writing is transported beyond representation to an operational horizon, where it builds what it says, immediately. Language that cannot follow it along this path is already a husk – inconsequential by essence – unless politics can save it. (Bitcoin is the bet that it cannot.)

§0.042 — Even when not explicitly referencing a text, and thus evoking the gap between word and thing, the name ‘Bitcoin’ remains divided by a fatal difference (one of still greater importance to our discussion). The initial, narrow, version of this rift – distinguishing any quantity of bitcoins from the comprehensive singularity of Bitcoin – is a critical faultline to which we will repeatedly return.footnote:[The distinction between “lowercase bitcoin and Initial-Cap Bitcoin” (in the words of Terrence Yang), i.e. “digital money” and “a protocol” respectively, has already been impressively standardized. The emulation of a philosophical difference – and, as moderns, we can confidently say the philosophical difference – by a terminological convention rapidly settled within the worlds of technological commentary and financial news media attests to a determination of conceptuality from the outside. The ‘thought’ that matters is produced in advance of any explicitly philosophical apprehension. (This fatality will no doubt evoke Hegel’s “Owl of Minerva” among those receptive to speculative communization, whose problems will be touched upon later in this book.) For Terrence Yang’s articulation of Bitcoin’s ontological difference, link:http://www.quora.com/What-is-bitcoin-and-its-significance-in-physical-world/answer/Terrence-Yang-4?srid=3W9X[see].] It anticipates – while remaining irreducible to – a schism, of gathering social concreteness and historical consequence, opened by the polarization of ‘Bitcoin’ (conceived as specific, contingent, branded, and politically- or competitively-extinguishable) over against ‘the blockchain’ (a generic technological innovation, that is accepted as irreversible, and promoted as conservatively-assimilable). Threading through the most energized Bitcoin debates is a question of limitation. Can the currency system be circumscribed (and then transcended), as the larval stage of something greater than itself – serving as the historical ‘bootloader’ for a new Internet revolution driven by generic blockchain-based trustless transactions protocols? The philosophical rift re-activating transcendental-empirical difference in the domain of monetary technology has thus already been dramatically opened and even tentatively evaluated in the course of a process of widely-reported, financially-invested, socio-economic exploration, before any self-conscious philosophical activity reaches it. During the elaboration of this controversy, some of the crucial interests at stake in Bitcoin’s inner rift have been exposed, and their theoretical absorption facilitated. The fact that the question has been raised by opportunistic venture capital does nothing at all to detract from its perfectly philosophical character, as captured – with reasonable fidelity – by the formulation: What are the limits of Bitcoin?

§0.043 — It is at the third – and fully historical – level of meaning, however, that the ultimate scope of Bitcoin’s significance is gradually manifested. Beyond the initial formulation (or abstract protocol), and its subsequent implementation as a functioning currency system (and already something more), there emerges a far broader Bitcoin installation process,footnote:[Eminent wave theorist Carlota Perez insists upon the historical integrity of technology and finance within ‘great surges of development’, each of which introduces a new ‘techno-economic paradigm’. She first divides each surge into an ‘installation phase’ and a ‘deployment phase’ (each in turn is tractable to binary sub-division), noting that the transition from one to the other is typically marked by an investment-overshoot driven financial crisis. Political economy is a rhythm. Its pulse, with roughly half-century periodicity, encompasses not only techno-industrial innovation and its financing, but also social sentiment and political animation. The history of capitalism is thus constructed as a succession of comparatively discrete stages. Each of Perez’s ‘great surges of development’ corresponds to a complex telic object. The language of ‘installation’ already says as much. Some virtual thing arrives, or is put into place. (These terminologies are strictly inter-changeable.) On the basis of the most mechanical reading of Perez’s supple analytical framework, something corresponding to a Bitcoin ‘deployment phase’ might be expected in the 2030-2040s. Such a time-table assumes an absence of techonomic acceleration at the deepest level of the modernization: a negative prediction which Perez’s historical analysis as a whole supports. The Great Waves of development are paced by an anthropomorphic-generational temporality, rather than a self-propelling momentum inherent to mechanical industrialism. They are not speeding up. Comparatively stable periodicity is essential to the hypothesis. Crypto-Current is not a documentation of the Bitcoin installation process, although it grants – without reservation – the potential value of such a work. There is perhaps nothing that would more incisively capture the deepest principles of the rising capitalist wave. Functional trustlessness, as an industrial output, remains only very tentatively conceived. The momentum behind it is difficult to easily overestimate. With the emergence of Bitcoin, rigorously constitutional governance, a political-economic problem that the old liberal order found impossible to successfully navigate, has transitioned into a techonomic capability under automatic propulsion. Industrialization of government is the definite implication. Quite clearly, the socio-political stake in a capitalist development wave can never have been higher. Regimes, potentially, are now business outputs.] of evidently vast but still-obscure character and magnitude. The formula is a diagram, the implementation is an active database supporting a crypto-currency, but what undergoes installation is an entire techonomic ‘ecology’ or ‘infrastructure’ – a complex manifold of interlocking parts, whose horizons are still lost to us in hazy distances (however rapidly we are hurtling into them). It is on this dimension that Bitcoin and Philosophy is most clearly and comprehensively overwhelmed. After being thought, and then done, Bitcoin promises – or threatens – to change the way everything is thought and done, or would be thought to do so, were it not that in the age of code such dulled terms have outlived their usefulness, and persist only through inertia.

§0.05 — Bitcoin machines value. It follows that the prevailing conception of technology as instrumental capability, subsumed under extrinsic ends, is among the very many things to fall by the wayside as the process escalates. Traditional categories of thought (or conception) and action (or performance) are mutually subsumed into an irreducible cognitive action. The strengthening diagonal current passing between the notional and the actual, ‘ought’ and ‘is’, intelligence and mechanism – which in its aporetic articulation has been the exquisite torture of postmodern philosophy – is simply code. Bitcoin ushers this cryptic fatality into simultaneous conceptual and mechanical consummation.

§0.051 — It is necessary to go further. In the final analysis, nothing less than the nature of reality is brought into question by this event. It concerns the ‘Being of beings’ (at least). If the claim seems extravagant, it is nevertheless inescapable, once the transcendental status of an ultimate criterion based upon absolute succession is granted to the Bitcoin protocol. It is not only that no higher tribunal exists. When envisaged at a sufficient level of abstraction, no higher tribunal could possibly exist. The Bitcoin ledger is the first intrinsically reliable record. It is now known what happened, without argument. This is a situation without precedent which also reaches – immediately – an absolute limit, in principle. It thus exemplifies the synthetic a priori. There is no philosophical thinking of Bitcoin – in either the subjective or objective genitive – that is not also (‘simultaneously’) a re-thinking of time, or sovereign decision. ‘Re-thinking’ is a revision, but no less a restoration. Bitcoin introduces us to a time-machine, or time-synthesizer, which can only complicate any initial intuitions about its novelty. It has been on the way for centuries (at least). This will, in any case, constitute the stubborn, guiding assertion of the book.

§0.06 — Crypto-Current is organized into six sections, which together compose a cycle. The analytically dismantled circuit of Bitcoin – with each segment seized as a philosophical provocation – finally closes upon itself in an attestation of its positive groundlessness. The loop of Bitcoin auto-production knows nothing of transcendence, at any stage. Whatever might have sought to intrude, representing an extrinsic authority, is dismissed as a superfluous ‘trusted third party’. The circuit is the entire thing.

§0.061 — On the path to a philosophical hash of Bitcoin as a transcendental horizon, Crypto-Current commits itself to a number of interlocking but isolable propositions. Among these, the most intensely exploited – which is to say, those found indispensable for our purposes – are advanced here, in the approximate order of their introduction. Compressed in this way, they can only appear ill-grounded, or dogmatic. They are anticipated in this way for the purposes of convenient preparation, not persuasion. (Digits from the first decimal place map to sections of this book where the relevant discussion is found.)

§0.1 — Chapter One provides an introduction. It takes a short Satoshi Nakamoto text footnote:[‘Bitcoin P2P e-cash paper’ (2008/11/01) https://www.mail-archive.com/cryptography@metzdowd.com/msg09959.html] as its point of departure, in order to capture Bitcoin as larva.footnote:[A larva is a mask, and a cryptic (infolded) potentiality.] Its intimate relation with the history of cryptography is supplemented by something hidden, working out through it. Word becomes code.

§0.11 — At the beginning there is a yet-underestimated philosophical work. Whatever happens to Bitcoin, its status as a decisively important document will be secure. Furthermore, reflexively, what is meant by a ‘document’ will never again be the same, after logical envelopment by the category of the ledger entry. Documentation has crossed a new threshold of mechanization. Bitcoin the documentary is thus an exposé in which nothing is hidden, unless behind a fully-manifested mask. It binds publicity to security. All Bitcoin does is secure documentation, which is enough.

§0.12 — The entire cycle is captured by this preliminary diagram, as an “electronic cash system”. In the closure of this cycle, a rupture – or irreversible occurrence – has taken place, comparable in structure and scale to Gödelian transcendental arithmetic, and to Public Key Encryption. Money changes phase, with an abrupt radicality from which there can be no return. 